## Curso Python para Economistas
### Trabajo Práctico Nº 4

### Fecha de entrega:
Viernes 21/10 a las 17:00 hs

### Modalidad de entrega y trabajo
- Este TP es **grupal**. _Al definir los integrantes del grupo, tengan en cuenta los días de gracia disponibles que tiene cada uno_.
- Un miembro del grupo debe crear un repositorio **privado** en GitHub, y dar acceso a sus compañeros y a los 5 profesores.
- **Todos los miembros del grupo deben haber hecho al menos un commit con contribuciones sustanciales**. Tengan esto en cuenta especialmente si, por ejemplo, van a estar trabajando en una misma computadora.
- Corroborar que el nombre de usuario que tienen configurado para `git` es el mismo nombre de usuario de GitHub. Para hacer esto, se puede correr `git config --list` en `cmd` oterminal.
- Cuando hayan hecho ese último commit, copien la URL para clonar su repositorio y péguenla en
[este Google Sheet](https://docs.google.com/spreadsheets/d/1JmrvClRxxb3luzbDrzAMUC2cfQXyGIV0cev0JTi_Ff4/edit?usp=sharing), en la hoja del TP4. Agreguen los nombres de los integrantes del grupo. Al ser un repositorio privado, sólo los colaboradores habilitados podrán clonarlo.
- Al finalizar el trabajo práctico deben hacer un último commit y push en su repositorio de GitHub con el mensaje `"Entrega final del TP4"`. Antes de la fecha y hora de entrega pueden hacer cuantos cambios quieran en el repositorio, pero luego de la hora de corte no deben hacer más cambios. Si un commit con el mensaje anterior se realiza luego de la hora de entrega, se supondrá que la entrega tardía fue intencional y se utilizarán los días de gracia. La última versión en el repositorio es la que será evaluada. Para esto es importante que no completen el Google Sheet hasta que no hayan finalizado el TP, como tampoco hacer pushes posteriores a la entrega.

### Ejercicios

En el siguiente trabajo vamos a trabajar con datos de domicilios (muy) malformados, que se encuentran en el archivo `Clase4/TP4/domicilios.csv` de este repositorio.

Primero, leamos el contenido del archivo:

In [46]:
with open("domicilios.csv", encoding="latin1") as domicilios_f:
    domicilios = domicilios_f.readlines()
    header = domicilios.pop(0) # Quito el encabezado (primera línea) del archivo

In [47]:
# Se examina el contenido
domicilios

['342550;B° SAN LUIS XV(15);C: 03;;M: G;\n',
 '342551;B° J.DE DIOS GARRO;C: 04;;M:LL;\n',
 '342552;B° L.RODRIGUEZ;C: 05;;M: F;\n',
 '342553;B° SAN LUIS XV(15);C: 05;;M: E;\n',
 '342554;B° JARDIN DEL SUR;C: 06;;M: F;\n',
 '342555;B° EST.DEL SUR;C: 09;;M: A;\n',
 '342556;B° 109 VIV.;C: 1;;M: E;\n',
 '342557;B° 109 VIV.;C: 1;;M: E;\n',
 '342558;B° SAN LUIS XXIII;C: 1;;M: E;\n',
 '342559;B° L.RODRIGUEZ;C: 10;;M: Z;\n',
 '342560;B° 544 VIV.;C: 10;;MZ T;\n',
 '342561;B° SAN LUIS XV(15);C: 11;;M: N;\n',
 '342562;B° 544 VIV.;C: 11;;MZ T;\n',
 '342563;B° L.RODRIGUEZ;C: 12;;M: X;\n',
 '342564;B° JARDIN DEL SUR;C: 12;;M: D;\n',
 '342565;B° J.DE DIOS GARRO;C: 13;;M: Q;\n',
 '342566;B° EL HORNERO;C: 13;;M: A;\n',
 '342567;B° L.RODRIGUEZ;C: 13;;M: V;\n',
 '342568;B° PUCARA;C: 15;;M: A;\n',
 '342569;B° SAN LUIS XXIII;C: 17;;M: E;\n',
 '342570;B° PUCARA;C: 18;;M: B;\n',
 '342571;B° J.F.BOGADO;C: 18;;M: C;\n',
 '342572;B° SAN LUIS XV(15);C: 19;;M: K;\n',
 '342573;B° 200 VIV.SUR;C: 19;;M: A;\n',
 '342574;B° P.MUJICA;C: 2;;M: E;\n',
 '342575;B° SAN LUIS XV(15);C: 20;;M: G;\n',
 '342576;B° M.TORO;C: 20;;P;\n',
 '342577;B° M.TORO;C: 20;;M: I;\n',
 '342578;B° SAN LUIS XV(15);C: 22;;M: H;\n',
 '342579;B° P.MUJICA;C: 3;;M: F;\n',
 '342580;B° L.RODRIGUEZ;C: 4;;M: C;\n',
 '342581;B° J.DE DIOS GARRO;C: 5;;M. C3;\n',
 '342582;B° SAN LUIS XV(15);C: 5;;M: I;\n',
 '342583;B° VIRGEN DE LUJAN;C: 5;;M: B;\n',
 '342584;B° J.DE DIOS GARRO;C: 6;;M: N;\n',
 '342585;B° M.TIBILETTI;C: 639;;;\n',
 '342586;B° F.AMERICANOS;C: 7;;M: A;\n',
 '342587;B° 544 VIV.;C: 7;;MZ C;\n',
 '342588;B° 544 VIV.;C: 7;;MZ D;\n',
 '342589;B° F.AMERICANOS;C: 8;;M: C;\n',
 '342590;B° 544 VIV.;C: 9;;MZ C;\n',
 '342591;B° L.RODRIGUEZ;C.1;;;S\n',
 '342592;B° J.P.PAYER;M: 1;C: 2;;\n',
 '342593;B° 500 VIV.SUR;M: 108;C: 5;;\n',
 '342594;B° 500 VIV.SUR;M: 109;C: 12;;\n',
 '342595;B° S.PUNTANAS;M: 11;C: 10;;\n',
 '342596;B° 500 VIV.SUR;M: 117;C: 7;;\n',
 '342597;B° 500 VIV.SUR;M: 135;C: 13;;\n',
 '342598;B° EL LINCE;M: 14;C: 30;;\n',
 '342599;B° 500 VIV.SUR;M: 144;C: 14;;\n',
 '342600;B° 500 VIV.SUR;M: 150;C:6;;\n',
 '342601;B° 500 VIV.SUR;M: 156;C: 3;;\n',
 '342602;B° EL LINCE;M: 17;C: 11;;\n',
 '342603;B° ESTRELLA DEL SUR;M: 189;C: 11;;\n',
 '342604;B° EST.DEL SUR;M: 196;C: 13;;\n',
 '342605;B° 110 VIV.;M: 196;C: 25;;\n',
 '342606;B° SAN LUIS XXVI(26);M: 2;C: 27;;\n',
 '342607;B° S.PUNTANAS;M: 225;C: 8;;\n',
 '342608;B° S.PUNTANAS;M: 229;C: 13;;\n',
 '342609;B° S.PUNTANAS;M: 232;C: 10;;\n',
 '342610;B° S.PUNTANAS;M: 232;C: 8;;\n',
 '342611;B° N.KIRCHNER;M: 235;C: 17;;\n',
 '342612;B° M.DEL PORTEZUELO;M: 29;C: 4;;\n',
 '342613;B° EL LINCE;M: 36;C: 24;;\n',
 '342614;B° EL LINCE;M: 40;C: 29;;\n',
 '342615;B° EL HORNERO;M: 7;C: 13;;\n',
 '342616;B° F.AMERICANOS;M: 77;C: 11;;\n',
 '342617;B° 500 VIV.SUR;MZ.105;C.13;;\n',
 '342618;B° ESTRELLA DEL SUR;MZ.11;C.15;;\n',
 '342619;B° 111 VIV.;MZ.11 B;27;;\n',
 '342620;B° 500 VIV.SUR;MZ.151;C.20;;\n',
 '342621;B° M.DEL PORTEZUELO;MZ.2;11;;\n',
 '342622;B° N.KIRCHNER;MZ.233;C.6;;\n',
 '342623;B° N.KIRCHNER;MZ.235;C.3;;\n',
 '342624;B° S.PUNTANAS;MZ.237;C.8;;\n',
 '342625;B° S.PUNTANAS;MZ.237;18;;\n',
 '342626;B° EL FARO I;MZ.246;C.5;;\n',
 '342627;B° EL FARO I;MZ.248;C.14;;\n',
 '342628;B° M.DEL PORTEZUELO;MZ.31;C.7;;\n',
 '342629;B° S.PUNTANAS;MZ.34;5;;\n',
 '342630;B° S.PUNTANAS;MZ.9;C.20;;\n',
 '342631;RUTA PROV.N°19;S/N;;;\n',
 '342632;RUTA PROV.N°19;S/N;;;\n',
 '342633;B° 109 VIV.;S/N;C:5;;\n',
 '342634;B° S.PUNTANAS;S/N;;260;16\n',
 '342635;B° S.PUNTANAS;S/N;;248;6\n',
 '342636;B° S.PUNTANAS;S/N;;152;6\n',
 '342637;B° S.PUNTANAS;S/N;;260;16\n',
 '342638;B° S.PUNTANAS;S/N;;;\n',
 '342639;B° S.PUNTANAS;S/N;;;\n',
 '342640;B° S.PUNTANAS;S/N;;;\n',
 '342641;B° S.PUNTANAS;S/N;;;\n',
 '342642;B° P.MUJICA;S/N;;D;17\n',
 '342643;B° M.DEL PORTEZUELO;S/N;;;\n',
 '342644;B° M.DEL PORTEZUELO;S/N;;14;12\n',
 '342645;B° M.DEL PORTEZUELO;S/N;;;\n',
 '342646;B° 500 VIV.SUR;S/N;;123;2\n',
 '342647;B° 500 VIV.SUR;S/N;;;\n',
 '342648;B° 500 VIV.SUR;S/N;3;143;\n',
 '342649;B° 500 VIV.SUR;S/N;10;130;\n',
 '342650;T.ARGENTINOS;S/N;;;\n',
 '342651;T.ARGENTINOS;S/N;;;\n',
 '342652;B° J.F.BOGADO;S/N;;;\n',
 '342653;B° PUCARA;S/N;;;\n',
 '342654;MZA H CASA 5;S/N;;;\n',
 '342655;RUTA NAC.N°146;S/N;;;6\n',
 '342656;COSTANERA;S/N;;;\n',
 '342657;RUTA PROV.N°19;S/N;;;\n',
 '342658;CHACHO PEÑALOZA Y JULIO A ROCA;S/N;;;\n',
 '342659;RUTA 7 Y PEDRO VELAZQUEZ;S/N;;;\n',
 '342660;MZA 233 CASA 11;S/N;;;\n',
 '342661;MZA B CASA 1;S/N;;;\n',
 '342662;MZNA C CASA 11;S/N;;;\n',
 '342663;C.PEÑALOZA;S/N;;;\n',
 '342664;C.PEÑALOZA;S/N;;;\n',
 '342665;RUTA PROV.N°19;S/N;;;\n',
 '342666;O.V.ANDRADE;S/N;;;\n',
 '342667;EX ADUANA;S/N;;;\n',
 '342668;RIOBAMBA SUR;S/N;;;\n',
 '342669;PARCELA 9 MZNA 383;S/N;;;\n',
 '342670;GERBACIO ESCUDERO;S/N;;;\n',
 '342671;B° UNION ALLENDE;S/N;;;\n',
 '342672;AV.J.A.ROCA;S/N;;;\n',
 '342673;RUTA PROV. N° 3 KM 4 EXT SUR;S/N;;;\n',
 '342674;MZNA 15 CASA 14;S/N;;;\n',
 '342675;MZNA A CASA 05;S/N;;;\n',
 '342676;MZNA 110 CASA 16;S/N;;;\n',
 '342677;RIOBAMBA EXTREMO SUR;S/N;;;\n',
 '342678;12 KMS AL OESTE;S/N;;;\n',
 '342679;Bº 132 VIV M:;S/N;20;C;\n',
 '342680;MZNA A CASA 5;S/N;;;\n',
 '342681;B° SAN LUIS XV(15);S/N;13;A;\n',
 '342682;RUTA PROV.N° 3;S/N;;;\n',
 '342683;MANZ. D CASA 1;S/N;;;\n',
 '342684;MZNA 196 CASA 6;S/N;;;\n',
 '342685;RUTA PROV.N°19;S/N;;;\n',
 '342686;MZNA 195 CASA 14;S/N;;;\n',
 '342687;C.PEÑALOZA;S/N;;;\n',
 '342688;C.PEÑALOZA;S/N;;;\n',
 '342689;B° EL LINCE;S/N;;;\n',
 '342690;RUTA PROV.N° 3;S/N;;;\n',
 '342691;Bº L.RODRIGUEZ, MZ: P C:11A;S/N;;;\n',
 '342692;Bº EL HORNERO MZ:  C 02;S/N;;;\n',
 '342693;Bº SERRANIAS PUNTANAS MZAN 7 CASA 10;S/N;;;\n',
 '342694;B° LUCAS RODRIGUEZ MZ: S C:;S/N;;;\n',
 '342695;MANZANA 23 - CASA 15;S/N;;;\n',
 '342696;C.PEÑALOZA;S/N;;;\n',
 '342697;B° L.RODRIGUEZ;S/N;4;;\n',
 '342698;MZNA Z1 CASA 03;S/N;;;\n',
 '342699;RUTA PROV SUR KM 13 Y 1/2;S/N;;;\n',
 '342700;Bº LOS VAGONES CHACHO PEÑALOZA;S/N;;;\n',
 '342701;RUTA PROVINCIAL 3 SUR KM 13,5;S/N;;;\n',
 '342702;BøEL HORNERO MZ.A C.7;S/N;;MZ.A;\n',
 '342703;B° M TORO- MZ D- C.16;S/N;;;\n',
 '342704;B° EL HORNERO MZ:B;S/N;C:08;;\n',
 '342705;B° M.LEZCANO MZ:J CS:27;S/N;;;\n',
 '342706;B° EL LINCE MZ.24 CS.7;S/N;;;\n',
 '342707;Bø L.RODRIGUEZ M:;S/N;V C15;;\n',
 '342708;C.DEL ROSARIO;S/N;717;;\n',
 '342709;B° EL HORNERO M:;S/N;HC:19;;\n',
 '342710;B° SAN LUIS 23 MZ.E C.8;S/N;;MZ.E;\n',
 '342711;B° M.LEZCANO M:M C:15;S/N;;;\n',
 '342712;B° EL HORNERO MZ.D C.26;S/N;;MZ.D;\n',
 '342713;B° FELIX BOGADO M:O;S/N;C:11;;\n',
 '342714;B°L.RODRIGUEZ MZ.G C.21;S/N;;MZ.G;\n',
 '342715;B° J.F.BOGADO MZ.E CS.9;S/N;;MZ.E;\n',
 '342716;B° F.BOGADO MZ.I CS.8;S/N;;MZ.I;\n',
 '342717;Bø M.LEZCANO MZA.L CS.12;S/N;;;\n',
 '342718;B° EL HORNERO MZ.A C 22;S/N;;MZ.A;\n',
 '342719;Bø 544 VIV. MZ.E C.5;S/N;;MZ E;\n',
 '342720;B° EL LINCE MZ.30 CS.2;S/N;;;\n',
 '342721;Bø FELIZ BOGADO M:C C:3;S/N;;;\n',
 '342722;RUTA 3 KM.4 LOTE 60;S/N;;;\n',
 '342723;B° 544 VDAS MZ.D CS.23;S/N;;MZ D;\n',
 '342724;B° 544 VIV. M:C;S/N;C:07;;\n',
 '342725;B° J.F.BOGADO MZ.J CS.1;S/N;;;\n',
 '342726;B° L.RODRIGUEZ MZ.R CS.13;S/N;;;\n',
 '342727;B° J.DEL SUR MZ.D CS.21;S/N;;MZ.D;\n',
 '342728;B° SAN LUIS XV MZ:G;S/N;C:8;;\n',
 '342729;B° EL LINCE MZ.16 CS.25;S/N;;;\n',
 '342730;B°PUCARA MZ.B C.9;S/N;;MZ.B;\n',
 '342731;B° M.LEZCANO MZ:I CS:7;S/N;;;\n',
 '342732;B° J.DE DIOS GARRO MZ:D;S/N;C:4;;\n',
 '342733;B° M.TIBILETTI CALLE 45;S/N;C.595;;\n',
 '342734;B° EL HORNERO M:;S/N;D C11;;\n',
 '342735;B° PUCARA MZ.E;S/N;C:05;MZ.E;\n',
 '342736;B° J. DEL SUR M:H;S/N;C:19;;\n',
 '342737;B° EL HORNERO MZ.F CS. 9;S/N;;MZ.F;\n',
 '342738;B° E.DEL SUR MZA.E CS.76;S/N;;;\n',
 '342739;B° M.TORO MZ:LL;S/N;CS:1;;\n',
 '342740;BøLUCAS RODRIGUEZ M:X C:2;S/N;;;\n',
 '342741;PADRE MUGICA MZ:G;S/N;C:01;;\n',
 '342742;B° MANUEL LEZCANO MZA Ñ;S/N;C.10;;\n',
 '342743;B° 144 VDAS MZ B;S/N;C:8;;\n',
 '342744;B° 544 VIV. MZ.N CS.19;S/N;;;\n',
 '342745;B° MAXIMILIANO TORO M:K;S/N;C:20;;\n',
 '342746;B° M.TORO MZ.LL CS.12;S/N;;;\n',
 '342747;B° M.LEZCANO MZ.I CS.17;S/N;;MZ.I;\n',
 '342748;B° TIBILETTI CALLE 45;S/N;;;\n',
 '342749;Bø J.F.BOGADO;S/N;DC:6;;\n',
 '342750;B° 544 VIV. MZ:;S/N;A.C14;;\n',
 '342751;B° EL LINCE MZ.189 CS.23;S/N;;;\n',
 '342752;LUCAS RODRIGUEZ MZA Z;S/N;C:3;;\n',
 '342753;B° M.TORO MZ.G CS.23;S/N;;MZ.G;\n',
 '342754;B°EL HORNERO MZ.6 C.3;S/N;;;\n',
 '342755;Bø L.RODRIGUEZ M:;S/N;W C:8;;\n',
 '342756;B° M.LEZCANO MZ.B CS.8;S/N;;MZ.B;\n',
 '342757;B° M.LEZCANO MZ.G CS.2;S/N;;MZ.G;\n',
 '342758;Bø M.TORO;S/N;P C17;;\n',
 '342759;B° SAN LUIS XXVI(26) MZ.1;S/N;1 CS.;;\n',
 '342760;B° 544 VIV. MZ.R CS.8;S/N;;;\n',
 '342761;Bø SAN LUIS XV MZ.B CS.14;S/N;;MZ.B;\n',
 '342762;B° 544 VIV. MZ.M CS.2;S/N;;;\n',
 '342763;B° EL LINCE MZ.39 C.7;S/N;;;\n',
 '342764;B° SAN LUIS XV M:;S/N;N C18;;\n',
 '342765;B° J.F.BOGADO MZ.A CS.20;S/N;;MZ.A;\n',
 '342766;Bø J.F.BOGADO M:;S/N;Q C11;;\n',
 '342767;B° L.RODRIGUEZ MZ.U C.5;S/N;;;\n',
 '342768;B° M.LEZCANO MZ.H CS.25;S/N;;MZ.H;\n',
 '342769;B° J.DE DIOS GARRO MZ.M C;S/N;CS.15;;\n',
 '342770;B° J.DEL SUR M:B;S/N;C:04;;\n',
 '342771;B° EL LINCE MZ.14 CS.11;S/N;;;\n',
 '342772;B° J.F.BOGADO M:;S/N;F.C5;;\n',
 '342773;B° F.BOGADO MZ.N CS.27;S/N;;;\n',
 '342774;Bø S.LUIS XV MZ.L CS.24;S/N;;;\n',
 '342775;BøM.LEZCANO MZ:;S/N;E.C10;;\n',
 '342776;B° EL LINCE M:39 C:9;S/N;;;\n',
 '342777;B° M.TORO MZ.P CS.9;S/N;;;\n',
 '342778;B° JARDIN DEL SUR MZ.G CS;S/N;S.11;MZ.G;\n',
 '342779;B° J.F.BOGADO MZ:B CS:17;S/N;;;\n',
 '342780;B° VALLE DEL SOL M:;S/N;KC:16;;\n',
 '342781;B° J.F.BOGADO M:;S/N;N C:2;;\n',
 '342782;Bø ESTRELLA DEL SUR M:E;S/N;C:78;;\n',
 '342783;B° SAN LUIS XXVIMZ:3 CS:7;S/N;;;\n',
 '342784;B° L.RODRIGUEZ MZ.C CS.6;S/N;;MZ.C;\n',
 '342785;B° LUCAS RODRIGUEZ M:I 3;S/N;C:03;;\n',
 '342786;Bø SAN LUIS XXIII;S/N;E.C1;;\n',
 '342787;B°114 VIV.MZ.192 C.10;S/N;;;\n',
 '342788;B° EL LINCE, MZ.21, C.5;S/N;;;\n',
 '342789;B° L.RODRIGUEZ M:;S/N;Q C:3;;\n',
 '342790;ESTRELLA DEL SUR M:E;S/N;C:71;;\n',
 '342791;B° J.DE DIOS GARRO MZ.L C;S/N;CS.23;;\n',
 '342792;B° JARDIN DEL SUR M:E;S/N;C:4;;\n',
 '342793;B° M.LEZCANO MZ.M C.14;S/N;;;\n',
 '342794;B° M.TORO M:P C:5;S/N;;;\n',
 '342795;BøF.AMERICANOS MZ.A;S/N;C.01;MZ.A;\n',
 '342796;B°M.LEZCANO MZ.A C.6;S/N;;MZ.A;\n',
 '342797;B° L.RODRIGUEZ MZ.D CS.2;S/N;;MZ.D;\n',
 '342798;B° EL LINCE MZ.31 CS.15;S/N;;;\n',
 '342799;B° M.TORO MZ:O CS:17;S/N;;;\n',
 '342800;B° M.LEZCANO MZ.F CS.11;S/N;;MZ.F;\n',
 '342801;B° EL LINCE MZ.36 CS.29;S/N;;;\n',
 '342802;B° MANUEL LEZCANO MZ:B;S/N;CS:01;;\n',
 '342803;B° EL HORNERO M:B C:3;S/N;;;\n',
 '342804;B°J.DE DIOS GARRO M:M C:4;S/N;;;\n',
 '342805;Bø M.TORO M:;S/N;M C:4;;\n',
 '342806;B° J.F.BOGADO MZ.1 CS.14;S/N;;;\n',
 '342807;B° S.LUIS 26 MZ:4 CS:4;S/N;;;\n',
 '342808;B° EL LINCE MZ.18 CS.18;S/N;;;\n',
 '342809;Bø114 VIV. MZ.189 C.5;S/N;;;\n',
 '342810;Bø EL HORNERO MZ.B CS.6;S/N;;MZ.B;\n',
 '342811;B° MANUEL LEZCANO M:Ñ;S/N;C:05;;\n',
 '342812;B° LUCAS RODRIGUEZ M:;S/N;C C20;;\n',
 '342813;B° J.F.BOGADO MZ.I C.13;S/N;;MZ.I;\n',
 "342814;Bø 544 VIV.-M.'J'-C.26-;S/N;;;\n",
 '342815;B° M.TORO MZ.;S/N;E.C:1;;\n',
 '342816;B° L.RODRIGUEZ MZ.F CS.10;S/N;;MZ.F;\n',
 '342817;B° J.DE D.GARRO MZ.E5 C.1;S/N;;MZ.E;\n',
 '342818;B° EL HORNERO MZ.3 C.5;S/N;;;\n',
 '342819;B° M.TORO MZ.D CS.1;S/N;;MZ.D;\n',
 '342820;B° M.LEZCANO MZ.I CS.3;S/N;;MZ.I;\n',
 '342821;BøEL LINCE MZA 36;S/N;C.22;;\n',
 '342822;B° 110 VIV. MZ.44 CS.1;S/N;;;\n',
 '342823;B° EL HORNERO M: G;S/N;C:05;;\n',
 '342824;B° EL HORNERO MZ.D C.24;S/N;;MZ.D;\n',
 '342825;B° EL HORNERO M:I;S/N;C:22;;\n',
 '342826;Bø EL LINCE MZ:;S/N;26C19;;\n',
 '342827;B° M.TORO MZ.B CS.2;S/N;;MZ.B;\n',
 '342828;B° M.LEZCANO MZ:K CS:21;S/N;;;\n',
 '342829;B° M.TORO MZ.G CS.15;S/N;;MZ.G;\n',
 '342830;B° TIBILETTI COSTANERA SU;S/N;1600;;\n',
 '342831;Bø M.LEZCANO M:7 C:9;S/N;;;\n',
 '342832;PLAN JOVENES 25/35 M:;S/N;C C11;;\n',
 '342833;B° M, TORO MZ.1;S/N;;;\n',
 '342834;B° SERRANIAS PUNT M: 44;S/N;C: 5;;\n',
 '342835;B° EL LINCE M:24 C:2;S/N;;;\n',
 '342836;Bø J.F.BOGADO;S/N;C:2;;\n',
 '342837;B° EL LINCE- MZ 21- C.5;S/N;;;\n',
 '342838;B° EL LINCE JOSE ZAVALA;S/N;795;;\n',
 '342839;B° 544 VIV. MZ.M CS.23;S/N;;;\n',
 '342840;Bø J.F.BOGADO;S/N;RC:17;;\n',
 '342841;B° SAN LUIS 23 ZONA SUR M;S/N;E C27;;\n',
 '342842;B° MAXIMILIANO TORO;S/N;H C19;;\n',
 '342843;B° M.LEZCANO;S/N;E C13;;\n',
 '342844;B° J.DEL SUR MZ.B CS.2;S/N;;MZ.B;\n',
 '342845;B° 544 VV. M:E;S/N;C:06;;\n',
 '342846;Bø J.DE DIOS GARRO;S/N;F6 C8;;\n',
 '342847;B° 110 VIV. MZ.196 C.16;S/N;;;\n',
 '342848;B° L.RODRIGUEZ MZ.I CS.9;S/N;;MZ.I;\n',
 '342849;B° 544 VIV. MZ.U CS.17;S/N;;;\n',
 '342850;B L. RODRIGUEZ M:B C:17;S/N;;;\n',
 '342851;B° J.F.BOGADO MZ.LL CS.8;S/N;;;\n',
 '342852;B° L.RODRIGUEZ M:;S/N;R C12;;\n',
 '342853;B° LUCAS RODRIGUEZ M:;S/N;I C:5;;\n',
 '342854;CALLE:45 CS:1266;S/N;;;\n',
 '342855;BøM.TORO M:;S/N;L.C:8;;\n',
 '342856;BøJ.DEL D.GARRO M:P C:7;S/N;;;\n',
 '342857;B° SAN LUIS XV MZ: D;S/N;CS:17;;\n',
 '342858;B° M.TORO MZ.M CS.9;S/N;;;\n',
 '342859;B° 114 VIV. MZ.188 CS.2;S/N;;;\n',
 '342860;B° M.TORO MZ.L CS.14;S/N;;;\n',
 '342861;B° J.F.BOGADO MZ.A CS.26;S/N;;MZ.A;\n',
 '342862;B° J.DE DIOS GARRO MZ.C3;S/N;CS.17;MZ.C;\n',
 '342863;B° SAN LUIS XV(15) MZ.I C;S/N;CS.3;MZ.I;\n',
 '342864;B° SAN LUIS XV(15) MZ.L C;S/N;CS.11;;\n',
 '342865;BøF.BOGADO MZ.A C.1;S/N;;MZ.A;\n',
 '342866;B° M.LEZCANO MZ.L CS.16;S/N;;;\n',
 '342867;B° 544 VIV. M:C;S/N;C:14;;\n',
 '342868;B° JARDIN DEL SUR M:;S/N;C C13;;\n',
 '342869;B° M.TORO MZ.C CS.12;S/N;;MZ.C;\n',
 '342870;B°JARDIN SUR MZ.G C.5;S/N;;MZ.G;\n',
 '342871;B° 110 VIV. M:194 C:13;S/N;;;\n',
 '342872;B° J.DEL SUR M:;S/N;I C27;;\n',
 '342873;B° J.F.BOGADO MZ.G CS.12;S/N;;MZ.G;\n',
 '342874;B° J.F.BOGADO MZ.M C.17;S/N;;;\n',
 '342875;B° L.RODRIGUEZ MZ:H CS:3;S/N;;;\n',
 '342876;Bø L.RODRIGUEZ MZ.A CS.27;S/N;;MZ.A;\n',
 '342877;B°E.DEL SUR M:;S/N;EC:61;;\n',
 '342878;Bø J.F.BOGADO M:;S/N;CC:28;;\n',
 '342879;B°J.DE DIOS GARRO M:;S/N;A1C11;;\n',
 '342880;B°F.BOGADO MZ.K C.27;S/N;;;\n',
 '342881;B° M.LEZCANO MZ:K;S/N;C:13;;\n',
 '342882;Bø SAN LUIS XV M:K;S/N;C:4;;\n',
 '342883;B° J.F.BOGADO MZ.L CS.24;S/N;;;\n',
 '342884;B° L.RODRIGUEZ MZ.I 9 CS.;S/N;1;MZ.I;\n',
 '342885;B° EL HORNERO MZ:D;S/N;C:18;;\n',
 '342886;B° EL HORNERO M:;S/N;E C26;;\n',
 '342887;B° SAN LUIS 23 M:B CS:3;S/N;;;\n',
 '342888;EL HORNERO;S/N;H-08;;\n',
 '342889;B° SAN LUIS XV(15) M:;S/N;JC:18;;\n',
 '342890;Bø.E.DEL SUR MZ:;S/N;F.C81;;\n',
 '342891;Bø M.TORO M:;S/N;G C17;;\n',
 '342892;B° L.RODRIGUEZ MZ.W CS.11;S/N;;;\n',
 '342893;B° EL HORNERO MZ.F CS.13;S/N;;MZ.F;\n',
 '342894;B° J.F.BOGADO MZ.Q CS.3;S/N;;;\n',
 '342895;B° 544 VIV. MZ.N CS.25;S/N;;;\n',
 '342896;B° PUCARA MZ.F CS.12;S/N;;MZ.F;\n',
 '342897;B° J.F.BOGADO MZ.K C.21;S/N;;;\n',
 '342898;B° M.TORO M:F;S/N;C:1;;\n',
 '342899;MANUEL LESCANO MZ. I C.N.;S/N;;;\n',
 '342900;B° J.DEL SUR MZ.D CS.11;S/N;;MZ.D;\n',
 '342901;B° 544 VDAS MZ.C CS.13;S/N;;MZ C;\n',
 '342902;B° SAN LUIS XXVI M:5 C:5;S/N;;;\n',
 '342903;B° VIRGEN DE LUJAN M:C;S/N;C:29;;\n',
 '342904;B° EL HORNERO MZ.C CS.27;S/N;;MZ.C;\n',
 '342905;B°J.DE DIOS GARRO MZ.C 14;S/N;;MZ.C;\n',
 '342906;Bø MANUEL LEZCANO MZ: L;S/N;C: 20;;\n',
 '342907;B° F.AMERICANOS MZ.B;S/N;CS.15;MZ.B;\n',
 '342908;B°L.RODRIGUEZ MZ.I CS.2;S/N;;MZ.I;\n',
 '342909;B° 109 VIV.M:B C:20;S/N;;;\n',
 '342910;B° EL LINCE MZ.23 CS.26;S/N;;;\n',
 '342911;B°PUCARA M:;S/N;F C21;;\n',
 '342912;B° EL LINCE MZ.24 CS.14;S/N;;;\n',
 '342913;Bø JARDIN DEL SUR M:D;S/N;C:9;;\n',
 '342914;RUTA 3 KM. 4;S/N;;;\n',
 '342915;B° EL LINCE MZ.20 CS.9;S/N;;;\n',
 '342916;BøEL LINCE MZ.23 CS.22;S/N;;;\n',
 '342917;Bø L.RODRIGUEZ MZA. U;S/N;C.11;;\n',
 '342918;B° 544 VIV. MZ.I CS.13;S/N;;MZ I;\n',
 '342919;SALVADOR SEGADO;S/N;C.9;;\n',
 '342920;Bø EL HORNERO MZ.J CS.14;S/N;;;\n',
 '342921;B° 110 VIV. MZ.191 CS.12;S/N;;;\n',
 '342922;B° SAN LUIS XV(15) M:;S/N;J C:3;;\n',
 '342923;B° E,DEL SUR MZA.E CS.59;S/N;;;\n',
 '342924;B°SAN LUIS XV MZ.J C.23;S/N;;;\n',
 '342925;B° EL HORNERO MZ.B C.2;S/N;;MZ.B;\n',
 '342926;BøEL HORNERO MZ.G C.2;S/N;;MZ.G;\n',
 '342927;B° 544 VDAS M:;S/N;N C:3;;\n',
 '342928;B° 500 VDAS M:143 C:15;S/N;;;\n',
 '342929;B° ESTRELLA DEL SUR MZA A;S/N;C:8;;\n',
 '342930;MAXIMILIANO TORO MZ: M;S/N;C:06;;\n',
 '342931;BøS.LUIS XXIII MZ:C :;S/N;C:7;;\n',
 '342932;MANUEL LEZCANO M: C;S/N;C:5;;\n',
 '342933;RUTA 3 KM 12;S/N;;;\n',
 '342934;B° MANUEL LEZCANO M:;S/N;D C:7;;\n',
 '342935;544 VIVIENDAS MZA F;S/N;C:21;;\n',
 '342936;B° J.F.BOGADO MZ.LL CS.7;S/N;;;\n',
 '342937;B° 200 VIV.MUNICIPAL M:B;S/N;C:21;;\n',
 '342938;B° JARDIN DEL SUR;S/N;G C13;;\n',
 '342939;B° M.LEZCANO MZ.G CS.8;S/N;;MZ.G;\n',
 '342940;B° J.F.BOGADO MZ.K CS.6;S/N;;;\n',
 '342941;B° M.TORO MZ.Q C.14;S/N;;;\n',
 '342942;B° EL HORNERO MZ.E CS.2;S/N;;MZ.E;\n',
 '342943;B° J.F.BOGADO MZ.C CS.23;S/N;;MZ.C;\n',
 '342944;B° L.RODRIGUEZ MZ.G CS.4;S/N;;MZ.G;\n',
 '342945;Bø J.DEL SUR M:;S/N;D C:1;;\n',
 '342946;B° 144 VIV. M:;S/N;C C16;;\n',
 '342947;B° 500 VIV SUR M;S/N;161C6;;\n',
 '342948;B° J.F.BOGADO MZ.O C.36;S/N;;;\n',
 '342949;B°L.RODRIGUEZ MZ.H C.14;S/N;;MZ.H;\n',
 '342950;Bø PUCARA;S/N;BC:12;;\n',
 '342951;B° JARDIN DEL SUR MZ.B CS;S/N;23;MZ.B;\n',
 '342952;B° FELIX BOGADO M:C;S/N;C:07;;\n',
 '342953;B° M.TORO MZ.I CS.20;S/N;;MZ.I;\n',
 '342954;B°EL LINCE MZ.18 CS.22;S/N;;;\n',
 '342955;Bø M.TORO MZ.L CS.2;S/N;;;\n',
 '342956;SAN LUIS 26 MZ:3 CS:17;S/N;;;\n',
 '342957;B°EL HORNERO MZ.I C.12;S/N;;MZ.I;\n',
 '342958;B°EL LINCE M:30 C:5;S/N;;;\n',
 '342959;B° FELIX BOGADO M:C;S/N;C:14;;\n',
 '342960;B° J.DEL SUR MZ.G CS.6;S/N;;MZ.G;\n',
 '342961;B° LUCAS RODRIGUEZ M: Z;S/N;C:13;;\n',
 '342962;B°S.LUIS XV MZ.H C.26;S/N;;MZ.H;\n',
 '342963;B° M.LEZCANO MZ.M CS.22;S/N;;;\n',
 '342964;BøEL LINCE M:40 C:9;S/N;;;\n',
 '342965;B° J. DE DIOS GARRO M:F6;S/N;C:15;;\n',
 '342966;B°J.DEL SUR MZ.E C.20;S/N;;MZ.E;\n',
 '342967;LUCAS RODRIGUEZ MZ G;S/N;C:22;;\n',
 '342968;B° SAN LUIS XV MZ.Ñ CS.19;S/N;;;\n',
 '342969;B° 544 MZ.E C.22;S/N;;MZ E;\n',
 '342970;B° JARDIN SUR MZ.H C.17;S/N;;MZ.H;\n',
 '342971;B° L.RODRIGUEZ MZ.Z C.5;S/N;;;\n',
 '342972;B°L.RODRIGUEZ MZ.S C.12;S/N;;;\n',
 '342973;B° EL LINCE MZ.26 C.22;S/N;;;\n',
 '342974;B° M.LEZCANO MZ.C CS.10;S/N;;MZ.C;\n',
 '342975;B° S.LUIS 15 M:L C:20;S/N;;;\n',
 '342976;B° L.RODRIGUEZ M:P;S/N;C:19;;\n',
 '342977;B° M.TORO MZ.Q C.3;S/N;;;\n',
 '342978;Bø109 VDAS MZ.C CS.9;S/N;;MZ.C;\n',
 '342979;Bø109 VIV.MZ:;S/N;FC:18;;\n',
 '342980;B° J.F.BOGADO M:K C:14;S/N;;;\n',
 '342981;B° LUCAS RODRIGUEZ- MZ F;S/N;C 5;;\n',
 '342982;B° EL LINCE MZ.24 CS.16;S/N;;;\n',
 '342983;B° EL LINCE M:40 C:29;S/N;;;\n',
 '342984;B°S.LUIS 15 MZ.K C.18;S/N;;;\n',
 '342985;B°PUCARA M.E C.1;S/N;;;\n',
 '342986;Bø PUCARA MZ.A C.25;S/N;;MZ.A;\n',
 '342987;B° EL HORNERO M:H;S/N;C: 18;;\n',
 '342988;B° PUCARA MZ.F CS.1;S/N;;MZ.F;\n',
 '342989;B°F.BOGADO MZ:;S/N;K C:4;;\n',
 '342990;B° J.F.BOGADO M:E C:3;S/N;;;\n',
 '342991;B°EL LINCE MZ.31 C.5;S/N;;;\n',
 '342992;B°EL HORNERO M:;S/N;I C19;;\n',
 '342993;Bø EL LINCE-M.25-C.17-;S/N;;;\n',
 '342994;B° SAN LUIS XV(15) MZ.C C;S/N;CS.22;MZ.C;\n',
 '342995;B° ESTRELLA DEL SUR MZ:E;S/N;C:76;;\n',
 '342996;B° 110 VIV. MZ.194 CS.1;S/N;;;\n',
 '342997;B° EL LINCE MZ.20 CS.19;S/N;;;\n',
 '342998;B° SAN LUIS 23 MZA.;S/N;A C.3;;\n',
 '342999;B° L.RODRIGUEZ MZ.C CS.13;S/N;;MZ.C;\n',
 '343000;Bø 544 VIV.M:;S/N;D C20;;\n',
 '343001;B° E.DEL SUR M:;S/N;C C40;;\n',
 '343002;B° J.F.BOGADO MZ.H CS.13;S/N;;MZ.H;\n',
 '343003;B° M.TORO MZ.P CS.2;S/N;;;\n',
 '343004;B° J.DE DIOS GARRO M:Ñ;S/N;C:23;;\n',
 '343005;B° SAN LUIS XV(15) MZA G;S/N;C:18;;\n',
 '343006;B°PUCARA MZ.A CS.31;S/N;;MZ.A;\n',
 '343007;B° JARDIN DEL SUR MZ.D;S/N;C:15;MZ.D;\n',
 '343008;B° EL LINCE MZ:19 CS:2;S/N;;;\n',
 '343009;B° L.RODRIGUEZ MZ.W CS.3;S/N;;;\n',
 '343010;Bø SAN LUIS 15 M:;S/N;F C:5;;\n',
 '343011;B° EL LINCE MZ.19 C.22;S/N;;;\n',
 '343012;B° PUCARA MZ.B C.14;S/N;;MZ.B;\n',
 '343013;B° J.DE DIOS GARRO;S/N;N C:2;;\n',
 '343014;B° M.LEZCANO MZ.A CS.10;S/N;;MZ.A;\n',
 '343015;B°EL LINCE MZ.15 C.12;S/N;;;\n',
 '343016;B° EL HORNERO MZ:A CS:9;S/N;;;\n',
 '343017;B° E.DEL SUR MZ:E CS:74;S/N;;;\n',

La mayoría de las líneas contienen el ID del domicilio, el nombre de un barrio, el número de manzana y el número de casa. Vamos a enfocarnos sólo en las que tienen estos campos. 

Notar que los nombres de los barrios suelen estar precedidos por `B`, `Bº` o similar; los códigos de manzana (que pueden ser letras, números o combinaciones) por `M`, `MZ`, `MZA` o similar (seguido de espacios, `.`, `:`, etc.); y los números de casa por `C`, `CS`, `CSA`, `CASA` o similar; pero hay una gran variedad.


Además, la manzana y la casa no aparecen siempre en ese orden.

El objetivo de este trabajo es utilizar expresiones regulares para _parsear_ estos strings y darles un formato estructurado. _Notar que no vamos a intentar parsear todos los domicilios. Esta sería una tarea imposible, porque están realmente muy malformados._ La idea es utilizar lo que aprendimos para parsear un buen número de ellos, con la ayuda de widgets.

### Consignas

1. Utilizar el método [`strip`](https://docs.python.org/3/library/stdtypes.html#str.strip) de `string`'s para quitar el salto de línea final (`"\n"`) de cada elemento de la lista.

In [48]:
# "domicilios" es una lista de strings, por lo que genero una nueva lista donde a cada elemento le quito el string "\n"
domicilios_v1 = [s.strip("\n") for s in domicilios]
domicilios_v1

['342550;B° SAN LUIS XV(15);C: 03;;M: G;',
 '342551;B° J.DE DIOS GARRO;C: 04;;M:LL;',
 '342552;B° L.RODRIGUEZ;C: 05;;M: F;',
 '342553;B° SAN LUIS XV(15);C: 05;;M: E;',
 '342554;B° JARDIN DEL SUR;C: 06;;M: F;',
 '342555;B° EST.DEL SUR;C: 09;;M: A;',
 '342556;B° 109 VIV.;C: 1;;M: E;',
 '342557;B° 109 VIV.;C: 1;;M: E;',
 '342558;B° SAN LUIS XXIII;C: 1;;M: E;',
 '342559;B° L.RODRIGUEZ;C: 10;;M: Z;',
 '342560;B° 544 VIV.;C: 10;;MZ T;',
 '342561;B° SAN LUIS XV(15);C: 11;;M: N;',
 '342562;B° 544 VIV.;C: 11;;MZ T;',
 '342563;B° L.RODRIGUEZ;C: 12;;M: X;',
 '342564;B° JARDIN DEL SUR;C: 12;;M: D;',
 '342565;B° J.DE DIOS GARRO;C: 13;;M: Q;',
 '342566;B° EL HORNERO;C: 13;;M: A;',
 '342567;B° L.RODRIGUEZ;C: 13;;M: V;',
 '342568;B° PUCARA;C: 15;;M: A;',
 '342569;B° SAN LUIS XXIII;C: 17;;M: E;',
 '342570;B° PUCARA;C: 18;;M: B;',
 '342571;B° J.F.BOGADO;C: 18;;M: C;',
 '342572;B° SAN LUIS XV(15);C: 19;;M: K;',
 '342573;B° 200 VIV.SUR;C: 19;;M: A;',
 '342574;B° P.MUJICA;C: 2;;M: E;',
 '342575;B° SAN LUIS XV(15);C: 20;;M: G;',
 '342576;B° M.TORO;C: 20;;P;',
 '342577;B° M.TORO;C: 20;;M: I;',
 '342578;B° SAN LUIS XV(15);C: 22;;M: H;',
 '342579;B° P.MUJICA;C: 3;;M: F;',
 '342580;B° L.RODRIGUEZ;C: 4;;M: C;',
 '342581;B° J.DE DIOS GARRO;C: 5;;M. C3;',
 '342582;B° SAN LUIS XV(15);C: 5;;M: I;',
 '342583;B° VIRGEN DE LUJAN;C: 5;;M: B;',
 '342584;B° J.DE DIOS GARRO;C: 6;;M: N;',
 '342585;B° M.TIBILETTI;C: 639;;;',
 '342586;B° F.AMERICANOS;C: 7;;M: A;',
 '342587;B° 544 VIV.;C: 7;;MZ C;',
 '342588;B° 544 VIV.;C: 7;;MZ D;',
 '342589;B° F.AMERICANOS;C: 8;;M: C;',
 '342590;B° 544 VIV.;C: 9;;MZ C;',
 '342591;B° L.RODRIGUEZ;C.1;;;S',
 '342592;B° J.P.PAYER;M: 1;C: 2;;',
 '342593;B° 500 VIV.SUR;M: 108;C: 5;;',
 '342594;B° 500 VIV.SUR;M: 109;C: 12;;',
 '342595;B° S.PUNTANAS;M: 11;C: 10;;',
 '342596;B° 500 VIV.SUR;M: 117;C: 7;;',
 '342597;B° 500 VIV.SUR;M: 135;C: 13;;',
 '342598;B° EL LINCE;M: 14;C: 30;;',
 '342599;B° 500 VIV.SUR;M: 144;C: 14;;',
 '342600;B° 500 VIV.SUR;M: 150;C:6;;',
 '342601;B° 500 VIV.SUR;M: 156;C: 3;;',
 '342602;B° EL LINCE;M: 17;C: 11;;',
 '342603;B° ESTRELLA DEL SUR;M: 189;C: 11;;',
 '342604;B° EST.DEL SUR;M: 196;C: 13;;',
 '342605;B° 110 VIV.;M: 196;C: 25;;',
 '342606;B° SAN LUIS XXVI(26);M: 2;C: 27;;',
 '342607;B° S.PUNTANAS;M: 225;C: 8;;',
 '342608;B° S.PUNTANAS;M: 229;C: 13;;',
 '342609;B° S.PUNTANAS;M: 232;C: 10;;',
 '342610;B° S.PUNTANAS;M: 232;C: 8;;',
 '342611;B° N.KIRCHNER;M: 235;C: 17;;',
 '342612;B° M.DEL PORTEZUELO;M: 29;C: 4;;',
 '342613;B° EL LINCE;M: 36;C: 24;;',
 '342614;B° EL LINCE;M: 40;C: 29;;',
 '342615;B° EL HORNERO;M: 7;C: 13;;',
 '342616;B° F.AMERICANOS;M: 77;C: 11;;',
 '342617;B° 500 VIV.SUR;MZ.105;C.13;;',
 '342618;B° ESTRELLA DEL SUR;MZ.11;C.15;;',
 '342619;B° 111 VIV.;MZ.11 B;27;;',
 '342620;B° 500 VIV.SUR;MZ.151;C.20;;',
 '342621;B° M.DEL PORTEZUELO;MZ.2;11;;',
 '342622;B° N.KIRCHNER;MZ.233;C.6;;',
 '342623;B° N.KIRCHNER;MZ.235;C.3;;',
 '342624;B° S.PUNTANAS;MZ.237;C.8;;',
 '342625;B° S.PUNTANAS;MZ.237;18;;',
 '342626;B° EL FARO I;MZ.246;C.5;;',
 '342627;B° EL FARO I;MZ.248;C.14;;',
 '342628;B° M.DEL PORTEZUELO;MZ.31;C.7;;',
 '342629;B° S.PUNTANAS;MZ.34;5;;',
 '342630;B° S.PUNTANAS;MZ.9;C.20;;',
 '342631;RUTA PROV.N°19;S/N;;;',
 '342632;RUTA PROV.N°19;S/N;;;',
 '342633;B° 109 VIV.;S/N;C:5;;',
 '342634;B° S.PUNTANAS;S/N;;260;16',
 '342635;B° S.PUNTANAS;S/N;;248;6',
 '342636;B° S.PUNTANAS;S/N;;152;6',
 '342637;B° S.PUNTANAS;S/N;;260;16',
 '342638;B° S.PUNTANAS;S/N;;;',
 '342639;B° S.PUNTANAS;S/N;;;',
 '342640;B° S.PUNTANAS;S/N;;;',
 '342641;B° S.PUNTANAS;S/N;;;',
 '342642;B° P.MUJICA;S/N;;D;17',
 '342643;B° M.DEL PORTEZUELO;S/N;;;',
 '342644;B° M.DEL PORTEZUELO;S/N;;14;12',
 '342645;B° M.DEL PORTEZUELO;S/N;;;',
 '342646;B° 500 VIV.SUR;S/N;;123;2',
 '342647;B° 500 VIV.SUR;S/N;;;',
 '342648;B° 500 VIV.SUR;S/N;3;143;',
 '342649;B° 500 VIV.SUR;S/N;10;130;',
 '342650;T.ARGENTINOS;S/N;;;',
 '342651;T.ARGENTINOS;S/N;;;',
 '342652;B° J.F.BOGADO;S/N;;;',
 '342653;B° PUCARA;S/N;;;',
 '342654;MZA H CASA 5;S/N;;;',
 '342655;RUTA NAC.N°146;S/N;;;6',
 '342656;COSTANERA;S/N;;;',
 '342657;RUTA PROV.N°19;S/N;;;',
 '342658;CHACHO PEÑALOZA Y JULIO A ROCA;S/N;;;',
 '342659;RUTA 7 Y PEDRO VELAZQUEZ;S/N;;;',
 '342660;MZA 233 CASA 11;S/N;;;',
 '342661;MZA B CASA 1;S/N;;;',
 '342662;MZNA C CASA 11;S/N;;;',
 '342663;C.PEÑALOZA;S/N;;;',
 '342664;C.PEÑALOZA;S/N;;;',
 '342665;RUTA PROV.N°19;S/N;;;',
 '342666;O.V.ANDRADE;S/N;;;',
 '342667;EX ADUANA;S/N;;;',
 '342668;RIOBAMBA SUR;S/N;;;',
 '342669;PARCELA 9 MZNA 383;S/N;;;',
 '342670;GERBACIO ESCUDERO;S/N;;;',
 '342671;B° UNION ALLENDE;S/N;;;',
 '342672;AV.J.A.ROCA;S/N;;;',
 '342673;RUTA PROV. N° 3 KM 4 EXT SUR;S/N;;;',
 '342674;MZNA 15 CASA 14;S/N;;;',
 '342675;MZNA A CASA 05;S/N;;;',
 '342676;MZNA 110 CASA 16;S/N;;;',
 '342677;RIOBAMBA EXTREMO SUR;S/N;;;',
 '342678;12 KMS AL OESTE;S/N;;;',
 '342679;Bº 132 VIV M:;S/N;20;C;',
 '342680;MZNA A CASA 5;S/N;;;',
 '342681;B° SAN LUIS XV(15);S/N;13;A;',
 '342682;RUTA PROV.N° 3;S/N;;;',
 '342683;MANZ. D CASA 1;S/N;;;',
 '342684;MZNA 196 CASA 6;S/N;;;',
 '342685;RUTA PROV.N°19;S/N;;;',
 '342686;MZNA 195 CASA 14;S/N;;;',
 '342687;C.PEÑALOZA;S/N;;;',
 '342688;C.PEÑALOZA;S/N;;;',
 '342689;B° EL LINCE;S/N;;;',
 '342690;RUTA PROV.N° 3;S/N;;;',
 '342691;Bº L.RODRIGUEZ, MZ: P C:11A;S/N;;;',
 '342692;Bº EL HORNERO MZ:  C 02;S/N;;;',
 '342693;Bº SERRANIAS PUNTANAS MZAN 7 CASA 10;S/N;;;',
 '342694;B° LUCAS RODRIGUEZ MZ: S C:;S/N;;;',
 '342695;MANZANA 23 - CASA 15;S/N;;;',
 '342696;C.PEÑALOZA;S/N;;;',
 '342697;B° L.RODRIGUEZ;S/N;4;;',
 '342698;MZNA Z1 CASA 03;S/N;;;',
 '342699;RUTA PROV SUR KM 13 Y 1/2;S/N;;;',
 '342700;Bº LOS VAGONES CHACHO PEÑALOZA;S/N;;;',
 '342701;RUTA PROVINCIAL 3 SUR KM 13,5;S/N;;;',
 '342702;BøEL HORNERO MZ.A C.7;S/N;;MZ.A;',
 '342703;B° M TORO- MZ D- C.16;S/N;;;',
 '342704;B° EL HORNERO MZ:B;S/N;C:08;;',
 '342705;B° M.LEZCANO MZ:J CS:27;S/N;;;',
 '342706;B° EL LINCE MZ.24 CS.7;S/N;;;',
 '342707;Bø L.RODRIGUEZ M:;S/N;V C15;;',
 '342708;C.DEL ROSARIO;S/N;717;;',
 '342709;B° EL HORNERO M:;S/N;HC:19;;',
 '342710;B° SAN LUIS 23 MZ.E C.8;S/N;;MZ.E;',
 '342711;B° M.LEZCANO M:M C:15;S/N;;;',
 '342712;B° EL HORNERO MZ.D C.26;S/N;;MZ.D;',
 '342713;B° FELIX BOGADO M:O;S/N;C:11;;',
 '342714;B°L.RODRIGUEZ MZ.G C.21;S/N;;MZ.G;',
 '342715;B° J.F.BOGADO MZ.E CS.9;S/N;;MZ.E;',
 '342716;B° F.BOGADO MZ.I CS.8;S/N;;MZ.I;',
 '342717;Bø M.LEZCANO MZA.L CS.12;S/N;;;',
 '342718;B° EL HORNERO MZ.A C 22;S/N;;MZ.A;',
 '342719;Bø 544 VIV. MZ.E C.5;S/N;;MZ E;',
 '342720;B° EL LINCE MZ.30 CS.2;S/N;;;',
 '342721;Bø FELIZ BOGADO M:C C:3;S/N;;;',
 '342722;RUTA 3 KM.4 LOTE 60;S/N;;;',
 '342723;B° 544 VDAS MZ.D CS.23;S/N;;MZ D;',
 '342724;B° 544 VIV. M:C;S/N;C:07;;',
 '342725;B° J.F.BOGADO MZ.J CS.1;S/N;;;',
 '342726;B° L.RODRIGUEZ MZ.R CS.13;S/N;;;',
 '342727;B° J.DEL SUR MZ.D CS.21;S/N;;MZ.D;',
 '342728;B° SAN LUIS XV MZ:G;S/N;C:8;;',
 '342729;B° EL LINCE MZ.16 CS.25;S/N;;;',
 '342730;B°PUCARA MZ.B C.9;S/N;;MZ.B;',
 '342731;B° M.LEZCANO MZ:I CS:7;S/N;;;',
 '342732;B° J.DE DIOS GARRO MZ:D;S/N;C:4;;',
 '342733;B° M.TIBILETTI CALLE 45;S/N;C.595;;',
 '342734;B° EL HORNERO M:;S/N;D C11;;',
 '342735;B° PUCARA MZ.E;S/N;C:05;MZ.E;',
 '342736;B° J. DEL SUR M:H;S/N;C:19;;',
 '342737;B° EL HORNERO MZ.F CS. 9;S/N;;MZ.F;',
 '342738;B° E.DEL SUR MZA.E CS.76;S/N;;;',
 '342739;B° M.TORO MZ:LL;S/N;CS:1;;',
 '342740;BøLUCAS RODRIGUEZ M:X C:2;S/N;;;',
 '342741;PADRE MUGICA MZ:G;S/N;C:01;;',
 '342742;B° MANUEL LEZCANO MZA Ñ;S/N;C.10;;',
 '342743;B° 144 VDAS MZ B;S/N;C:8;;',
 '342744;B° 544 VIV. MZ.N CS.19;S/N;;;',
 '342745;B° MAXIMILIANO TORO M:K;S/N;C:20;;',
 '342746;B° M.TORO MZ.LL CS.12;S/N;;;',
 '342747;B° M.LEZCANO MZ.I CS.17;S/N;;MZ.I;',
 '342748;B° TIBILETTI CALLE 45;S/N;;;',
 '342749;Bø J.F.BOGADO;S/N;DC:6;;',
 '342750;B° 544 VIV. MZ:;S/N;A.C14;;',
 '342751;B° EL LINCE MZ.189 CS.23;S/N;;;',
 '342752;LUCAS RODRIGUEZ MZA Z;S/N;C:3;;',
 '342753;B° M.TORO MZ.G CS.23;S/N;;MZ.G;',
 '342754;B°EL HORNERO MZ.6 C.3;S/N;;;',
 '342755;Bø L.RODRIGUEZ M:;S/N;W C:8;;',
 '342756;B° M.LEZCANO MZ.B CS.8;S/N;;MZ.B;',
 '342757;B° M.LEZCANO MZ.G CS.2;S/N;;MZ.G;',
 '342758;Bø M.TORO;S/N;P C17;;',
 '342759;B° SAN LUIS XXVI(26) MZ.1;S/N;1 CS.;;',
 '342760;B° 544 VIV. MZ.R CS.8;S/N;;;',
 '342761;Bø SAN LUIS XV MZ.B CS.14;S/N;;MZ.B;',
 '342762;B° 544 VIV. MZ.M CS.2;S/N;;;',
 '342763;B° EL LINCE MZ.39 C.7;S/N;;;',
 '342764;B° SAN LUIS XV M:;S/N;N C18;;',
 '342765;B° J.F.BOGADO MZ.A CS.20;S/N;;MZ.A;',
 '342766;Bø J.F.BOGADO M:;S/N;Q C11;;',
 '342767;B° L.RODRIGUEZ MZ.U C.5;S/N;;;',
 '342768;B° M.LEZCANO MZ.H CS.25;S/N;;MZ.H;',
 '342769;B° J.DE DIOS GARRO MZ.M C;S/N;CS.15;;',
 '342770;B° J.DEL SUR M:B;S/N;C:04;;',
 '342771;B° EL LINCE MZ.14 CS.11;S/N;;;',
 '342772;B° J.F.BOGADO M:;S/N;F.C5;;',
 '342773;B° F.BOGADO MZ.N CS.27;S/N;;;',
 '342774;Bø S.LUIS XV MZ.L CS.24;S/N;;;',
 '342775;BøM.LEZCANO MZ:;S/N;E.C10;;',
 '342776;B° EL LINCE M:39 C:9;S/N;;;',
 '342777;B° M.TORO MZ.P CS.9;S/N;;;',
 '342778;B° JARDIN DEL SUR MZ.G CS;S/N;S.11;MZ.G;',
 '342779;B° J.F.BOGADO MZ:B CS:17;S/N;;;',
 '342780;B° VALLE DEL SOL M:;S/N;KC:16;;',
 '342781;B° J.F.BOGADO M:;S/N;N C:2;;',
 '342782;Bø ESTRELLA DEL SUR M:E;S/N;C:78;;',
 '342783;B° SAN LUIS XXVIMZ:3 CS:7;S/N;;;',
 '342784;B° L.RODRIGUEZ MZ.C CS.6;S/N;;MZ.C;',
 '342785;B° LUCAS RODRIGUEZ M:I 3;S/N;C:03;;',
 '342786;Bø SAN LUIS XXIII;S/N;E.C1;;',
 '342787;B°114 VIV.MZ.192 C.10;S/N;;;',
 '342788;B° EL LINCE, MZ.21, C.5;S/N;;;',
 '342789;B° L.RODRIGUEZ M:;S/N;Q C:3;;',
 '342790;ESTRELLA DEL SUR M:E;S/N;C:71;;',
 '342791;B° J.DE DIOS GARRO MZ.L C;S/N;CS.23;;',
 '342792;B° JARDIN DEL SUR M:E;S/N;C:4;;',
 '342793;B° M.LEZCANO MZ.M C.14;S/N;;;',
 '342794;B° M.TORO M:P C:5;S/N;;;',
 '342795;BøF.AMERICANOS MZ.A;S/N;C.01;MZ.A;',
 '342796;B°M.LEZCANO MZ.A C.6;S/N;;MZ.A;',
 '342797;B° L.RODRIGUEZ MZ.D CS.2;S/N;;MZ.D;',
 '342798;B° EL LINCE MZ.31 CS.15;S/N;;;',
 '342799;B° M.TORO MZ:O CS:17;S/N;;;',
 '342800;B° M.LEZCANO MZ.F CS.11;S/N;;MZ.F;',
 '342801;B° EL LINCE MZ.36 CS.29;S/N;;;',
 '342802;B° MANUEL LEZCANO MZ:B;S/N;CS:01;;',
 '342803;B° EL HORNERO M:B C:3;S/N;;;',
 '342804;B°J.DE DIOS GARRO M:M C:4;S/N;;;',
 '342805;Bø M.TORO M:;S/N;M C:4;;',
 '342806;B° J.F.BOGADO MZ.1 CS.14;S/N;;;',
 '342807;B° S.LUIS 26 MZ:4 CS:4;S/N;;;',
 '342808;B° EL LINCE MZ.18 CS.18;S/N;;;',
 '342809;Bø114 VIV. MZ.189 C.5;S/N;;;',
 '342810;Bø EL HORNERO MZ.B CS.6;S/N;;MZ.B;',
 '342811;B° MANUEL LEZCANO M:Ñ;S/N;C:05;;',
 '342812;B° LUCAS RODRIGUEZ M:;S/N;C C20;;',
 '342813;B° J.F.BOGADO MZ.I C.13;S/N;;MZ.I;',
 "342814;Bø 544 VIV.-M.'J'-C.26-;S/N;;;",
 '342815;B° M.TORO MZ.;S/N;E.C:1;;',
 '342816;B° L.RODRIGUEZ MZ.F CS.10;S/N;;MZ.F;',
 '342817;B° J.DE D.GARRO MZ.E5 C.1;S/N;;MZ.E;',
 '342818;B° EL HORNERO MZ.3 C.5;S/N;;;',
 '342819;B° M.TORO MZ.D CS.1;S/N;;MZ.D;',
 '342820;B° M.LEZCANO MZ.I CS.3;S/N;;MZ.I;',
 '342821;BøEL LINCE MZA 36;S/N;C.22;;',
 '342822;B° 110 VIV. MZ.44 CS.1;S/N;;;',
 '342823;B° EL HORNERO M: G;S/N;C:05;;',
 '342824;B° EL HORNERO MZ.D C.24;S/N;;MZ.D;',
 '342825;B° EL HORNERO M:I;S/N;C:22;;',
 '342826;Bø EL LINCE MZ:;S/N;26C19;;',
 '342827;B° M.TORO MZ.B CS.2;S/N;;MZ.B;',
 '342828;B° M.LEZCANO MZ:K CS:21;S/N;;;',
 '342829;B° M.TORO MZ.G CS.15;S/N;;MZ.G;',
 '342830;B° TIBILETTI COSTANERA SU;S/N;1600;;',
 '342831;Bø M.LEZCANO M:7 C:9;S/N;;;',
 '342832;PLAN JOVENES 25/35 M:;S/N;C C11;;',
 '342833;B° M, TORO MZ.1;S/N;;;',
 '342834;B° SERRANIAS PUNT M: 44;S/N;C: 5;;',
 '342835;B° EL LINCE M:24 C:2;S/N;;;',
 '342836;Bø J.F.BOGADO;S/N;C:2;;',
 '342837;B° EL LINCE- MZ 21- C.5;S/N;;;',
 '342838;B° EL LINCE JOSE ZAVALA;S/N;795;;',
 '342839;B° 544 VIV. MZ.M CS.23;S/N;;;',
 '342840;Bø J.F.BOGADO;S/N;RC:17;;',
 '342841;B° SAN LUIS 23 ZONA SUR M;S/N;E C27;;',
 '342842;B° MAXIMILIANO TORO;S/N;H C19;;',
 '342843;B° M.LEZCANO;S/N;E C13;;',
 '342844;B° J.DEL SUR MZ.B CS.2;S/N;;MZ.B;',
 '342845;B° 544 VV. M:E;S/N;C:06;;',
 '342846;Bø J.DE DIOS GARRO;S/N;F6 C8;;',
 '342847;B° 110 VIV. MZ.196 C.16;S/N;;;',
 '342848;B° L.RODRIGUEZ MZ.I CS.9;S/N;;MZ.I;',
 '342849;B° 544 VIV. MZ.U CS.17;S/N;;;',
 '342850;B L. RODRIGUEZ M:B C:17;S/N;;;',
 '342851;B° J.F.BOGADO MZ.LL CS.8;S/N;;;',
 '342852;B° L.RODRIGUEZ M:;S/N;R C12;;',
 '342853;B° LUCAS RODRIGUEZ M:;S/N;I C:5;;',
 '342854;CALLE:45 CS:1266;S/N;;;',
 '342855;BøM.TORO M:;S/N;L.C:8;;',
 '342856;BøJ.DEL D.GARRO M:P C:7;S/N;;;',
 '342857;B° SAN LUIS XV MZ: D;S/N;CS:17;;',
 '342858;B° M.TORO MZ.M CS.9;S/N;;;',
 '342859;B° 114 VIV. MZ.188 CS.2;S/N;;;',
 '342860;B° M.TORO MZ.L CS.14;S/N;;;',
 '342861;B° J.F.BOGADO MZ.A CS.26;S/N;;MZ.A;',
 '342862;B° J.DE DIOS GARRO MZ.C3;S/N;CS.17;MZ.C;',
 '342863;B° SAN LUIS XV(15) MZ.I C;S/N;CS.3;MZ.I;',
 '342864;B° SAN LUIS XV(15) MZ.L C;S/N;CS.11;;',
 '342865;BøF.BOGADO MZ.A C.1;S/N;;MZ.A;',
 '342866;B° M.LEZCANO MZ.L CS.16;S/N;;;',
 '342867;B° 544 VIV. M:C;S/N;C:14;;',
 '342868;B° JARDIN DEL SUR M:;S/N;C C13;;',
 '342869;B° M.TORO MZ.C CS.12;S/N;;MZ.C;',
 '342870;B°JARDIN SUR MZ.G C.5;S/N;;MZ.G;',
 '342871;B° 110 VIV. M:194 C:13;S/N;;;',
 '342872;B° J.DEL SUR M:;S/N;I C27;;',
 '342873;B° J.F.BOGADO MZ.G CS.12;S/N;;MZ.G;',
 '342874;B° J.F.BOGADO MZ.M C.17;S/N;;;',
 '342875;B° L.RODRIGUEZ MZ:H CS:3;S/N;;;',
 '342876;Bø L.RODRIGUEZ MZ.A CS.27;S/N;;MZ.A;',
 '342877;B°E.DEL SUR M:;S/N;EC:61;;',
 '342878;Bø J.F.BOGADO M:;S/N;CC:28;;',
 '342879;B°J.DE DIOS GARRO M:;S/N;A1C11;;',
 '342880;B°F.BOGADO MZ.K C.27;S/N;;;',
 '342881;B° M.LEZCANO MZ:K;S/N;C:13;;',
 '342882;Bø SAN LUIS XV M:K;S/N;C:4;;',
 '342883;B° J.F.BOGADO MZ.L CS.24;S/N;;;',
 '342884;B° L.RODRIGUEZ MZ.I 9 CS.;S/N;1;MZ.I;',
 '342885;B° EL HORNERO MZ:D;S/N;C:18;;',
 '342886;B° EL HORNERO M:;S/N;E C26;;',
 '342887;B° SAN LUIS 23 M:B CS:3;S/N;;;',
 '342888;EL HORNERO;S/N;H-08;;',
 '342889;B° SAN LUIS XV(15) M:;S/N;JC:18;;',
 '342890;Bø.E.DEL SUR MZ:;S/N;F.C81;;',
 '342891;Bø M.TORO M:;S/N;G C17;;',
 '342892;B° L.RODRIGUEZ MZ.W CS.11;S/N;;;',
 '342893;B° EL HORNERO MZ.F CS.13;S/N;;MZ.F;',
 '342894;B° J.F.BOGADO MZ.Q CS.3;S/N;;;',
 '342895;B° 544 VIV. MZ.N CS.25;S/N;;;',
 '342896;B° PUCARA MZ.F CS.12;S/N;;MZ.F;',
 '342897;B° J.F.BOGADO MZ.K C.21;S/N;;;',
 '342898;B° M.TORO M:F;S/N;C:1;;',
 '342899;MANUEL LESCANO MZ. I C.N.;S/N;;;',
 '342900;B° J.DEL SUR MZ.D CS.11;S/N;;MZ.D;',
 '342901;B° 544 VDAS MZ.C CS.13;S/N;;MZ C;',
 '342902;B° SAN LUIS XXVI M:5 C:5;S/N;;;',
 '342903;B° VIRGEN DE LUJAN M:C;S/N;C:29;;',
 '342904;B° EL HORNERO MZ.C CS.27;S/N;;MZ.C;',
 '342905;B°J.DE DIOS GARRO MZ.C 14;S/N;;MZ.C;',
 '342906;Bø MANUEL LEZCANO MZ: L;S/N;C: 20;;',
 '342907;B° F.AMERICANOS MZ.B;S/N;CS.15;MZ.B;',
 '342908;B°L.RODRIGUEZ MZ.I CS.2;S/N;;MZ.I;',
 '342909;B° 109 VIV.M:B C:20;S/N;;;',
 '342910;B° EL LINCE MZ.23 CS.26;S/N;;;',
 '342911;B°PUCARA M:;S/N;F C21;;',
 '342912;B° EL LINCE MZ.24 CS.14;S/N;;;',
 '342913;Bø JARDIN DEL SUR M:D;S/N;C:9;;',
 '342914;RUTA 3 KM. 4;S/N;;;',
 '342915;B° EL LINCE MZ.20 CS.9;S/N;;;',
 '342916;BøEL LINCE MZ.23 CS.22;S/N;;;',
 '342917;Bø L.RODRIGUEZ MZA. U;S/N;C.11;;',
 '342918;B° 544 VIV. MZ.I CS.13;S/N;;MZ I;',
 '342919;SALVADOR SEGADO;S/N;C.9;;',
 '342920;Bø EL HORNERO MZ.J CS.14;S/N;;;',
 '342921;B° 110 VIV. MZ.191 CS.12;S/N;;;',
 '342922;B° SAN LUIS XV(15) M:;S/N;J C:3;;',
 '342923;B° E,DEL SUR MZA.E CS.59;S/N;;;',
 '342924;B°SAN LUIS XV MZ.J C.23;S/N;;;',
 '342925;B° EL HORNERO MZ.B C.2;S/N;;MZ.B;',
 '342926;BøEL HORNERO MZ.G C.2;S/N;;MZ.G;',
 '342927;B° 544 VDAS M:;S/N;N C:3;;',
 '342928;B° 500 VDAS M:143 C:15;S/N;;;',
 '342929;B° ESTRELLA DEL SUR MZA A;S/N;C:8;;',
 '342930;MAXIMILIANO TORO MZ: M;S/N;C:06;;',
 '342931;BøS.LUIS XXIII MZ:C :;S/N;C:7;;',
 '342932;MANUEL LEZCANO M: C;S/N;C:5;;',
 '342933;RUTA 3 KM 12;S/N;;;',
 '342934;B° MANUEL LEZCANO M:;S/N;D C:7;;',
 '342935;544 VIVIENDAS MZA F;S/N;C:21;;',
 '342936;B° J.F.BOGADO MZ.LL CS.7;S/N;;;',
 '342937;B° 200 VIV.MUNICIPAL M:B;S/N;C:21;;',
 '342938;B° JARDIN DEL SUR;S/N;G C13;;',
 '342939;B° M.LEZCANO MZ.G CS.8;S/N;;MZ.G;',
 '342940;B° J.F.BOGADO MZ.K CS.6;S/N;;;',
 '342941;B° M.TORO MZ.Q C.14;S/N;;;',
 '342942;B° EL HORNERO MZ.E CS.2;S/N;;MZ.E;',
 '342943;B° J.F.BOGADO MZ.C CS.23;S/N;;MZ.C;',
 '342944;B° L.RODRIGUEZ MZ.G CS.4;S/N;;MZ.G;',
 '342945;Bø J.DEL SUR M:;S/N;D C:1;;',
 '342946;B° 144 VIV. M:;S/N;C C16;;',
 '342947;B° 500 VIV SUR M;S/N;161C6;;',
 '342948;B° J.F.BOGADO MZ.O C.36;S/N;;;',
 '342949;B°L.RODRIGUEZ MZ.H C.14;S/N;;MZ.H;',
 '342950;Bø PUCARA;S/N;BC:12;;',
 '342951;B° JARDIN DEL SUR MZ.B CS;S/N;23;MZ.B;',
 '342952;B° FELIX BOGADO M:C;S/N;C:07;;',
 '342953;B° M.TORO MZ.I CS.20;S/N;;MZ.I;',
 '342954;B°EL LINCE MZ.18 CS.22;S/N;;;',
 '342955;Bø M.TORO MZ.L CS.2;S/N;;;',
 '342956;SAN LUIS 26 MZ:3 CS:17;S/N;;;',
 '342957;B°EL HORNERO MZ.I C.12;S/N;;MZ.I;',
 '342958;B°EL LINCE M:30 C:5;S/N;;;',
 '342959;B° FELIX BOGADO M:C;S/N;C:14;;',
 '342960;B° J.DEL SUR MZ.G CS.6;S/N;;MZ.G;',
 '342961;B° LUCAS RODRIGUEZ M: Z;S/N;C:13;;',
 '342962;B°S.LUIS XV MZ.H C.26;S/N;;MZ.H;',
 '342963;B° M.LEZCANO MZ.M CS.22;S/N;;;',
 '342964;BøEL LINCE M:40 C:9;S/N;;;',
 '342965;B° J. DE DIOS GARRO M:F6;S/N;C:15;;',
 '342966;B°J.DEL SUR MZ.E C.20;S/N;;MZ.E;',
 '342967;LUCAS RODRIGUEZ MZ G;S/N;C:22;;',
 '342968;B° SAN LUIS XV MZ.Ñ CS.19;S/N;;;',
 '342969;B° 544 MZ.E C.22;S/N;;MZ E;',
 '342970;B° JARDIN SUR MZ.H C.17;S/N;;MZ.H;',
 '342971;B° L.RODRIGUEZ MZ.Z C.5;S/N;;;',
 '342972;B°L.RODRIGUEZ MZ.S C.12;S/N;;;',
 '342973;B° EL LINCE MZ.26 C.22;S/N;;;',
 '342974;B° M.LEZCANO MZ.C CS.10;S/N;;MZ.C;',
 '342975;B° S.LUIS 15 M:L C:20;S/N;;;',
 '342976;B° L.RODRIGUEZ M:P;S/N;C:19;;',
 '342977;B° M.TORO MZ.Q C.3;S/N;;;',
 '342978;Bø109 VDAS MZ.C CS.9;S/N;;MZ.C;',
 '342979;Bø109 VIV.MZ:;S/N;FC:18;;',
 '342980;B° J.F.BOGADO M:K C:14;S/N;;;',
 '342981;B° LUCAS RODRIGUEZ- MZ F;S/N;C 5;;',
 '342982;B° EL LINCE MZ.24 CS.16;S/N;;;',
 '342983;B° EL LINCE M:40 C:29;S/N;;;',
 '342984;B°S.LUIS 15 MZ.K C.18;S/N;;;',
 '342985;B°PUCARA M.E C.1;S/N;;;',
 '342986;Bø PUCARA MZ.A C.25;S/N;;MZ.A;',
 '342987;B° EL HORNERO M:H;S/N;C: 18;;',
 '342988;B° PUCARA MZ.F CS.1;S/N;;MZ.F;',
 '342989;B°F.BOGADO MZ:;S/N;K C:4;;',
 '342990;B° J.F.BOGADO M:E C:3;S/N;;;',
 '342991;B°EL LINCE MZ.31 C.5;S/N;;;',
 '342992;B°EL HORNERO M:;S/N;I C19;;',
 '342993;Bø EL LINCE-M.25-C.17-;S/N;;;',
 '342994;B° SAN LUIS XV(15) MZ.C C;S/N;CS.22;MZ.C;',
 '342995;B° ESTRELLA DEL SUR MZ:E;S/N;C:76;;',
 '342996;B° 110 VIV. MZ.194 CS.1;S/N;;;',
 '342997;B° EL LINCE MZ.20 CS.19;S/N;;;',
 '342998;B° SAN LUIS 23 MZA.;S/N;A C.3;;',
 '342999;B° L.RODRIGUEZ MZ.C CS.13;S/N;;MZ.C;',
 '343000;Bø 544 VIV.M:;S/N;D C20;;',
 '343001;B° E.DEL SUR M:;S/N;C C40;;',
 '343002;B° J.F.BOGADO MZ.H CS.13;S/N;;MZ.H;',
 '343003;B° M.TORO MZ.P CS.2;S/N;;;',
 '343004;B° J.DE DIOS GARRO M:Ñ;S/N;C:23;;',
 '343005;B° SAN LUIS XV(15) MZA G;S/N;C:18;;',
 '343006;B°PUCARA MZ.A CS.31;S/N;;MZ.A;',
 '343007;B° JARDIN DEL SUR MZ.D;S/N;C:15;MZ.D;',
 '343008;B° EL LINCE MZ:19 CS:2;S/N;;;',
 '343009;B° L.RODRIGUEZ MZ.W CS.3;S/N;;;',
 '343010;Bø SAN LUIS 15 M:;S/N;F C:5;;',
 '343011;B° EL LINCE MZ.19 C.22;S/N;;;',
 '343012;B° PUCARA MZ.B C.14;S/N;;MZ.B;',
 '343013;B° J.DE DIOS GARRO;S/N;N C:2;;',
 '343014;B° M.LEZCANO MZ.A CS.10;S/N;;MZ.A;',
 '343015;B°EL LINCE MZ.15 C.12;S/N;;;',
 '343016;B° EL HORNERO MZ:A CS:9;S/N;;;',
 '343017;B° E.DEL SUR MZ:E CS:74;S/N;;;',
 '343018;B° EL LINCE MZ.40 CS.31;S/N;;;',
 '343019;B° EL LINCE MZ.23 CS.19;S/N;;;',
 '343020;BøEL LINCE MZ.36 C.4;S/N;;;',
 '343021;B° EL LINCE MZ.26 CS.1;S/N;;;',
 '343022;B° M.TIBILETTI;S/N;;;',
 '343023;B° M.LEZCANO MZ.I C.13;S/N;;MZ.I;',
 '343024;B° EL LINCE M:36 C:5;S/N;;;',
 '343025;B° EL HORNERO MZ 4 CS 9;S/N;;;',
 '343026;B° M.TORO MZ.G CS.2;S/N;;MZ.G;',
 '343027;B° EL HORNERO M:F;S/N;C:02;;',
 '343028;B° SAN LUIS XV(15) M:;S/N;CC:25;;',
 '343029;B° EL HORNERO MZ.C CS.25;S/N;;MZ.C;',
 '343030;B° L.RODRIGUEZ M:D;S/N;C:4;;',
 '343031;B° J.F.BOGADO MZ.B CS.5;S/N;;MZ.B;',
 '343032;B° EL HORNERO MZ.A CS.17;S/N;;MZ.A;',
 '343033;B° M.TIBILETTI CS.45;S/N;;;',
 '343034;B° SAN LUIS XVI M:02;S/N;C:05;;',
 '343035;109 VIVIENDAS M:;S/N;FC:10;;',
 '343036;B° SAN LUIS XV M:;S/N;I C:1;;',
 '343037;B° EL LINCE;S/N;;;',
 '343038;B° MANUEL LEZCANO M:N;S/N;C:13;;',
 '343039;B° MANUEL LEZCANO M:;S/N;H C28;;',
 '343040;B° 80 VIV M:;S/N;BC:18;;',

2. Separar el número que representa el ID del domicilio, del `string` que representa al domicilio en sí. El resultado debe ser una lista anidada, donde cada elemento de la lista maestra esté compuesto por estos dos componentes. Utilizar expresiones regulares y el método `group` para hacerlo.

In [49]:
# Importo la librería re
import re

# Creo una copia de la lista domicilios_v1 (lista original sin el salto de linea "\n" final) para poder modificarla
domicilios_v2 = domicilios_v1.copy()

# Genero un for loop que itere sobre los elementos de la lista domicilios_v2 separando, por un lado, el código de la dirección y, por el otro, la dirección propiamente dicha
for i in range(len(domicilios_v2)):
    domicilios_v2[i] = re.split("\d;", domicilios_v2[i], maxsplit=1)

# Inspeciono el nuevo dataframe
domicilios_v2

[['34255', 'B° SAN LUIS XV(15);C: 03;;M: G;'],
 ['34255', 'B° J.DE DIOS GARRO;C: 04;;M:LL;'],
 ['34255', 'B° L.RODRIGUEZ;C: 05;;M: F;'],
 ['34255', 'B° SAN LUIS XV(15);C: 05;;M: E;'],
 ['34255', 'B° JARDIN DEL SUR;C: 06;;M: F;'],
 ['34255', 'B° EST.DEL SUR;C: 09;;M: A;'],
 ['34255', 'B° 109 VIV.;C: 1;;M: E;'],
 ['34255', 'B° 109 VIV.;C: 1;;M: E;'],
 ['34255', 'B° SAN LUIS XXIII;C: 1;;M: E;'],
 ['34255', 'B° L.RODRIGUEZ;C: 10;;M: Z;'],
 ['34256', 'B° 544 VIV.;C: 10;;MZ T;'],
 ['34256', 'B° SAN LUIS XV(15);C: 11;;M: N;'],
 ['34256', 'B° 544 VIV.;C: 11;;MZ T;'],
 ['34256', 'B° L.RODRIGUEZ;C: 12;;M: X;'],
 ['34256', 'B° JARDIN DEL SUR;C: 12;;M: D;'],
 ['34256', 'B° J.DE DIOS GARRO;C: 13;;M: Q;'],
 ['34256', 'B° EL HORNERO;C: 13;;M: A;'],
 ['34256', 'B° L.RODRIGUEZ;C: 13;;M: V;'],
 ['34256', 'B° PUCARA;C: 15;;M: A;'],
 ['34256', 'B° SAN LUIS XXIII;C: 17;;M: E;'],
 ['34257', 'B° PUCARA;C: 18;;M: B;'],
 ['34257', 'B° J.F.BOGADO;C: 18;;M: C;'],
 ['34257', 'B° SAN LUIS XV(15);C: 19;;M: K;'],
 ['34257', 'B° 200 VIV.SUR;C: 19;;M: A;'],
 ['34257', 'B° P.MUJICA;C: 2;;M: E;'],
 ['34257', 'B° SAN LUIS XV(15);C: 20;;M: G;'],
 ['34257', 'B° M.TORO;C: 20;;P;'],
 ['34257', 'B° M.TORO;C: 20;;M: I;'],
 ['34257', 'B° SAN LUIS XV(15);C: 22;;M: H;'],
 ['34257', 'B° P.MUJICA;C: 3;;M: F;'],
 ['34258', 'B° L.RODRIGUEZ;C: 4;;M: C;'],
 ['34258', 'B° J.DE DIOS GARRO;C: 5;;M. C3;'],
 ['34258', 'B° SAN LUIS XV(15);C: 5;;M: I;'],
 ['34258', 'B° VIRGEN DE LUJAN;C: 5;;M: B;'],
 ['34258', 'B° J.DE DIOS GARRO;C: 6;;M: N;'],
 ['34258', 'B° M.TIBILETTI;C: 639;;;'],
 ['34258', 'B° F.AMERICANOS;C: 7;;M: A;'],
 ['34258', 'B° 544 VIV.;C: 7;;MZ C;'],
 ['34258', 'B° 544 VIV.;C: 7;;MZ D;'],
 ['34258', 'B° F.AMERICANOS;C: 8;;M: C;'],
 ['34259', 'B° 544 VIV.;C: 9;;MZ C;'],
 ['34259', 'B° L.RODRIGUEZ;C.1;;;S'],
 ['34259', 'B° J.P.PAYER;M: 1;C: 2;;'],
 ['34259', 'B° 500 VIV.SUR;M: 108;C: 5;;'],
 ['34259', 'B° 500 VIV.SUR;M: 109;C: 12;;'],
 ['34259', 'B° S.PUNTANAS;M: 11;C: 10;;'],
 ['34259', 'B° 500 VIV.SUR;M: 117;C: 7;;'],
 ['34259', 'B° 500 VIV.SUR;M: 135;C: 13;;'],
 ['34259', 'B° EL LINCE;M: 14;C: 30;;'],
 ['34259', 'B° 500 VIV.SUR;M: 144;C: 14;;'],
 ['34260', 'B° 500 VIV.SUR;M: 150;C:6;;'],
 ['34260', 'B° 500 VIV.SUR;M: 156;C: 3;;'],
 ['34260', 'B° EL LINCE;M: 17;C: 11;;'],
 ['34260', 'B° ESTRELLA DEL SUR;M: 189;C: 11;;'],
 ['34260', 'B° EST.DEL SUR;M: 196;C: 13;;'],
 ['34260', 'B° 110 VIV.;M: 196;C: 25;;'],
 ['34260', 'B° SAN LUIS XXVI(26);M: 2;C: 27;;'],
 ['34260', 'B° S.PUNTANAS;M: 225;C: 8;;'],
 ['34260', 'B° S.PUNTANAS;M: 229;C: 13;;'],
 ['34260', 'B° S.PUNTANAS;M: 232;C: 10;;'],
 ['34261', 'B° S.PUNTANAS;M: 232;C: 8;;'],
 ['34261', 'B° N.KIRCHNER;M: 235;C: 17;;'],
 ['34261', 'B° M.DEL PORTEZUELO;M: 29;C: 4;;'],
 ['34261', 'B° EL LINCE;M: 36;C: 24;;'],
 ['34261', 'B° EL LINCE;M: 40;C: 29;;'],
 ['34261', 'B° EL HORNERO;M: 7;C: 13;;'],
 ['34261', 'B° F.AMERICANOS;M: 77;C: 11;;'],
 ['34261', 'B° 500 VIV.SUR;MZ.105;C.13;;'],
 ['34261', 'B° ESTRELLA DEL SUR;MZ.11;C.15;;'],
 ['34261', 'B° 111 VIV.;MZ.11 B;27;;'],
 ['34262', 'B° 500 VIV.SUR;MZ.151;C.20;;'],
 ['34262', 'B° M.DEL PORTEZUELO;MZ.2;11;;'],
 ['34262', 'B° N.KIRCHNER;MZ.233;C.6;;'],
 ['34262', 'B° N.KIRCHNER;MZ.235;C.3;;'],
 ['34262', 'B° S.PUNTANAS;MZ.237;C.8;;'],
 ['34262', 'B° S.PUNTANAS;MZ.237;18;;'],
 ['34262', 'B° EL FARO I;MZ.246;C.5;;'],
 ['34262', 'B° EL FARO I;MZ.248;C.14;;'],
 ['34262', 'B° M.DEL PORTEZUELO;MZ.31;C.7;;'],
 ['34262', 'B° S.PUNTANAS;MZ.34;5;;'],
 ['34263', 'B° S.PUNTANAS;MZ.9;C.20;;'],
 ['34263', 'RUTA PROV.N°19;S/N;;;'],
 ['34263', 'RUTA PROV.N°19;S/N;;;'],
 ['34263', 'B° 109 VIV.;S/N;C:5;;'],
 ['34263', 'B° S.PUNTANAS;S/N;;260;16'],
 ['34263', 'B° S.PUNTANAS;S/N;;248;6'],
 ['34263', 'B° S.PUNTANAS;S/N;;152;6'],
 ['34263', 'B° S.PUNTANAS;S/N;;260;16'],
 ['34263', 'B° S.PUNTANAS;S/N;;;'],
 ['34263', 'B° S.PUNTANAS;S/N;;;'],
 ['34264', 'B° S.PUNTANAS;S/N;;;'],
 ['34264', 'B° S.PUNTANAS;S/N;;;'],
 ['34264', 'B° P.MUJICA;S/N;;D;17'],
 ['34264', 'B° M.DEL PORTEZUELO;S/N;;;'],
 ['34264', 'B° M.DEL PORTEZUELO;S/N;;14;12'],
 ['34264', 'B° M.DEL PORTEZUELO;S/N;;;'],
 ['34264', 'B° 500 VIV.SUR;S/N;;123;2'],
 ['34264', 'B° 500 VIV.SUR;S/N;;;'],
 ['34264', 'B° 500 VIV.SUR;S/N;3;143;'],
 ['34264', 'B° 500 VIV.SUR;S/N;10;130;'],
 ['34265', 'T.ARGENTINOS;S/N;;;'],
 ['34265', 'T.ARGENTINOS;S/N;;;'],
 ['34265', 'B° J.F.BOGADO;S/N;;;'],
 ['34265', 'B° PUCARA;S/N;;;'],
 ['34265', 'MZA H CASA 5;S/N;;;'],
 ['34265', 'RUTA NAC.N°146;S/N;;;6'],
 ['34265', 'COSTANERA;S/N;;;'],
 ['34265', 'RUTA PROV.N°19;S/N;;;'],
 ['34265', 'CHACHO PEÑALOZA Y JULIO A ROCA;S/N;;;'],
 ['34265', 'RUTA 7 Y PEDRO VELAZQUEZ;S/N;;;'],
 ['34266', 'MZA 233 CASA 11;S/N;;;'],
 ['34266', 'MZA B CASA 1;S/N;;;'],
 ['34266', 'MZNA C CASA 11;S/N;;;'],
 ['34266', 'C.PEÑALOZA;S/N;;;'],
 ['34266', 'C.PEÑALOZA;S/N;;;'],
 ['34266', 'RUTA PROV.N°19;S/N;;;'],
 ['34266', 'O.V.ANDRADE;S/N;;;'],
 ['34266', 'EX ADUANA;S/N;;;'],
 ['34266', 'RIOBAMBA SUR;S/N;;;'],
 ['34266', 'PARCELA 9 MZNA 383;S/N;;;'],
 ['34267', 'GERBACIO ESCUDERO;S/N;;;'],
 ['34267', 'B° UNION ALLENDE;S/N;;;'],
 ['34267', 'AV.J.A.ROCA;S/N;;;'],
 ['34267', 'RUTA PROV. N° 3 KM 4 EXT SUR;S/N;;;'],
 ['34267', 'MZNA 15 CASA 14;S/N;;;'],
 ['34267', 'MZNA A CASA 05;S/N;;;'],
 ['34267', 'MZNA 110 CASA 16;S/N;;;'],
 ['34267', 'RIOBAMBA EXTREMO SUR;S/N;;;'],
 ['34267', '12 KMS AL OESTE;S/N;;;'],
 ['34267', 'Bº 132 VIV M:;S/N;20;C;'],
 ['34268', 'MZNA A CASA 5;S/N;;;'],
 ['34268', 'B° SAN LUIS XV(15);S/N;13;A;'],
 ['34268', 'RUTA PROV.N° 3;S/N;;;'],
 ['34268', 'MANZ. D CASA 1;S/N;;;'],
 ['34268', 'MZNA 196 CASA 6;S/N;;;'],
 ['34268', 'RUTA PROV.N°19;S/N;;;'],
 ['34268', 'MZNA 195 CASA 14;S/N;;;'],
 ['34268', 'C.PEÑALOZA;S/N;;;'],
 ['34268', 'C.PEÑALOZA;S/N;;;'],
 ['34268', 'B° EL LINCE;S/N;;;'],
 ['34269', 'RUTA PROV.N° 3;S/N;;;'],
 ['34269', 'Bº L.RODRIGUEZ, MZ: P C:11A;S/N;;;'],
 ['34269', 'Bº EL HORNERO MZ:  C 02;S/N;;;'],
 ['34269', 'Bº SERRANIAS PUNTANAS MZAN 7 CASA 10;S/N;;;'],
 ['34269', 'B° LUCAS RODRIGUEZ MZ: S C:;S/N;;;'],
 ['34269', 'MANZANA 23 - CASA 15;S/N;;;'],
 ['34269', 'C.PEÑALOZA;S/N;;;'],
 ['34269', 'B° L.RODRIGUEZ;S/N;4;;'],
 ['34269', 'MZNA Z1 CASA 03;S/N;;;'],
 ['34269', 'RUTA PROV SUR KM 13 Y 1/2;S/N;;;'],
 ['34270', 'Bº LOS VAGONES CHACHO PEÑALOZA;S/N;;;'],
 ['34270', 'RUTA PROVINCIAL 3 SUR KM 13,5;S/N;;;'],
 ['34270', 'BøEL HORNERO MZ.A C.7;S/N;;MZ.A;'],
 ['34270', 'B° M TORO- MZ D- C.16;S/N;;;'],
 ['34270', 'B° EL HORNERO MZ:B;S/N;C:08;;'],
 ['34270', 'B° M.LEZCANO MZ:J CS:27;S/N;;;'],
 ['34270', 'B° EL LINCE MZ.24 CS.7;S/N;;;'],
 ['34270', 'Bø L.RODRIGUEZ M:;S/N;V C15;;'],
 ['34270', 'C.DEL ROSARIO;S/N;717;;'],
 ['34270', 'B° EL HORNERO M:;S/N;HC:19;;'],
 ['34271', 'B° SAN LUIS 23 MZ.E C.8;S/N;;MZ.E;'],
 ['34271', 'B° M.LEZCANO M:M C:15;S/N;;;'],
 ['34271', 'B° EL HORNERO MZ.D C.26;S/N;;MZ.D;'],
 ['34271', 'B° FELIX BOGADO M:O;S/N;C:11;;'],
 ['34271', 'B°L.RODRIGUEZ MZ.G C.21;S/N;;MZ.G;'],
 ['34271', 'B° J.F.BOGADO MZ.E CS.9;S/N;;MZ.E;'],
 ['34271', 'B° F.BOGADO MZ.I CS.8;S/N;;MZ.I;'],
 ['34271', 'Bø M.LEZCANO MZA.L CS.12;S/N;;;'],
 ['34271', 'B° EL HORNERO MZ.A C 22;S/N;;MZ.A;'],
 ['34271', 'Bø 544 VIV. MZ.E C.5;S/N;;MZ E;'],
 ['34272', 'B° EL LINCE MZ.30 CS.2;S/N;;;'],
 ['34272', 'Bø FELIZ BOGADO M:C C:3;S/N;;;'],
 ['34272', 'RUTA 3 KM.4 LOTE 60;S/N;;;'],
 ['34272', 'B° 544 VDAS MZ.D CS.23;S/N;;MZ D;'],
 ['34272', 'B° 544 VIV. M:C;S/N;C:07;;'],
 ['34272', 'B° J.F.BOGADO MZ.J CS.1;S/N;;;'],
 ['34272', 'B° L.RODRIGUEZ MZ.R CS.13;S/N;;;'],
 ['34272', 'B° J.DEL SUR MZ.D CS.21;S/N;;MZ.D;'],
 ['34272', 'B° SAN LUIS XV MZ:G;S/N;C:8;;'],
 ['34272', 'B° EL LINCE MZ.16 CS.25;S/N;;;'],
 ['34273', 'B°PUCARA MZ.B C.9;S/N;;MZ.B;'],
 ['34273', 'B° M.LEZCANO MZ:I CS:7;S/N;;;'],
 ['34273', 'B° J.DE DIOS GARRO MZ:D;S/N;C:4;;'],
 ['34273', 'B° M.TIBILETTI CALLE 45;S/N;C.595;;'],
 ['34273', 'B° EL HORNERO M:;S/N;D C11;;'],
 ['34273', 'B° PUCARA MZ.E;S/N;C:05;MZ.E;'],
 ['34273', 'B° J. DEL SUR M:H;S/N;C:19;;'],
 ['34273', 'B° EL HORNERO MZ.F CS. 9;S/N;;MZ.F;'],
 ['34273', 'B° E.DEL SUR MZA.E CS.76;S/N;;;'],
 ['34273', 'B° M.TORO MZ:LL;S/N;CS:1;;'],
 ['34274', 'BøLUCAS RODRIGUEZ M:X C:2;S/N;;;'],
 ['34274', 'PADRE MUGICA MZ:G;S/N;C:01;;'],
 ['34274', 'B° MANUEL LEZCANO MZA Ñ;S/N;C.10;;'],
 ['34274', 'B° 144 VDAS MZ B;S/N;C:8;;'],
 ['34274', 'B° 544 VIV. MZ.N CS.19;S/N;;;'],
 ['34274', 'B° MAXIMILIANO TORO M:K;S/N;C:20;;'],
 ['34274', 'B° M.TORO MZ.LL CS.12;S/N;;;'],
 ['34274', 'B° M.LEZCANO MZ.I CS.17;S/N;;MZ.I;'],
 ['34274', 'B° TIBILETTI CALLE 45;S/N;;;'],
 ['34274', 'Bø J.F.BOGADO;S/N;DC:6;;'],
 ['34275', 'B° 544 VIV. MZ:;S/N;A.C14;;'],
 ['34275', 'B° EL LINCE MZ.189 CS.23;S/N;;;'],
 ['34275', 'LUCAS RODRIGUEZ MZA Z;S/N;C:3;;'],
 ['34275', 'B° M.TORO MZ.G CS.23;S/N;;MZ.G;'],
 ['34275', 'B°EL HORNERO MZ.6 C.3;S/N;;;'],
 ['34275', 'Bø L.RODRIGUEZ M:;S/N;W C:8;;'],
 ['34275', 'B° M.LEZCANO MZ.B CS.8;S/N;;MZ.B;'],
 ['34275', 'B° M.LEZCANO MZ.G CS.2;S/N;;MZ.G;'],
 ['34275', 'Bø M.TORO;S/N;P C17;;'],
 ['34275', 'B° SAN LUIS XXVI(26) MZ.1;S/N;1 CS.;;'],
 ['34276', 'B° 544 VIV. MZ.R CS.8;S/N;;;'],
 ['34276', 'Bø SAN LUIS XV MZ.B CS.14;S/N;;MZ.B;'],
 ['34276', 'B° 544 VIV. MZ.M CS.2;S/N;;;'],
 ['34276', 'B° EL LINCE MZ.39 C.7;S/N;;;'],
 ['34276', 'B° SAN LUIS XV M:;S/N;N C18;;'],
 ['34276', 'B° J.F.BOGADO MZ.A CS.20;S/N;;MZ.A;'],
 ['34276', 'Bø J.F.BOGADO M:;S/N;Q C11;;'],
 ['34276', 'B° L.RODRIGUEZ MZ.U C.5;S/N;;;'],
 ['34276', 'B° M.LEZCANO MZ.H CS.25;S/N;;MZ.H;'],
 ['34276', 'B° J.DE DIOS GARRO MZ.M C;S/N;CS.15;;'],
 ['34277', 'B° J.DEL SUR M:B;S/N;C:04;;'],
 ['34277', 'B° EL LINCE MZ.14 CS.11;S/N;;;'],
 ['34277', 'B° J.F.BOGADO M:;S/N;F.C5;;'],
 ['34277', 'B° F.BOGADO MZ.N CS.27;S/N;;;'],
 ['34277', 'Bø S.LUIS XV MZ.L CS.24;S/N;;;'],
 ['34277', 'BøM.LEZCANO MZ:;S/N;E.C10;;'],
 ['34277', 'B° EL LINCE M:39 C:9;S/N;;;'],
 ['34277', 'B° M.TORO MZ.P CS.9;S/N;;;'],
 ['34277', 'B° JARDIN DEL SUR MZ.G CS;S/N;S.11;MZ.G;'],
 ['34277', 'B° J.F.BOGADO MZ:B CS:17;S/N;;;'],
 ['34278', 'B° VALLE DEL SOL M:;S/N;KC:16;;'],
 ['34278', 'B° J.F.BOGADO M:;S/N;N C:2;;'],
 ['34278', 'Bø ESTRELLA DEL SUR M:E;S/N;C:78;;'],
 ['34278', 'B° SAN LUIS XXVIMZ:3 CS:7;S/N;;;'],
 ['34278', 'B° L.RODRIGUEZ MZ.C CS.6;S/N;;MZ.C;'],
 ['34278', 'B° LUCAS RODRIGUEZ M:I 3;S/N;C:03;;'],
 ['34278', 'Bø SAN LUIS XXIII;S/N;E.C1;;'],
 ['34278', 'B°114 VIV.MZ.192 C.10;S/N;;;'],
 ['34278', 'B° EL LINCE, MZ.21, C.5;S/N;;;'],
 ['34278', 'B° L.RODRIGUEZ M:;S/N;Q C:3;;'],
 ['34279', 'ESTRELLA DEL SUR M:E;S/N;C:71;;'],
 ['34279', 'B° J.DE DIOS GARRO MZ.L C;S/N;CS.23;;'],
 ['34279', 'B° JARDIN DEL SUR M:E;S/N;C:4;;'],
 ['34279', 'B° M.LEZCANO MZ.M C.14;S/N;;;'],
 ['34279', 'B° M.TORO M:P C:5;S/N;;;'],
 ['34279', 'BøF.AMERICANOS MZ.A;S/N;C.01;MZ.A;'],
 ['34279', 'B°M.LEZCANO MZ.A C.6;S/N;;MZ.A;'],
 ['34279', 'B° L.RODRIGUEZ MZ.D CS.2;S/N;;MZ.D;'],
 ['34279', 'B° EL LINCE MZ.31 CS.15;S/N;;;'],
 ['34279', 'B° M.TORO MZ:O CS:17;S/N;;;'],
 ['34280', 'B° M.LEZCANO MZ.F CS.11;S/N;;MZ.F;'],
 ['34280', 'B° EL LINCE MZ.36 CS.29;S/N;;;'],
 ['34280', 'B° MANUEL LEZCANO MZ:B;S/N;CS:01;;'],
 ['34280', 'B° EL HORNERO M:B C:3;S/N;;;'],
 ['34280', 'B°J.DE DIOS GARRO M:M C:4;S/N;;;'],
 ['34280', 'Bø M.TORO M:;S/N;M C:4;;'],
 ['34280', 'B° J.F.BOGADO MZ.1 CS.14;S/N;;;'],
 ['34280', 'B° S.LUIS 26 MZ:4 CS:4;S/N;;;'],
 ['34280', 'B° EL LINCE MZ.18 CS.18;S/N;;;'],
 ['34280', 'Bø114 VIV. MZ.189 C.5;S/N;;;'],
 ['34281', 'Bø EL HORNERO MZ.B CS.6;S/N;;MZ.B;'],
 ['34281', 'B° MANUEL LEZCANO M:Ñ;S/N;C:05;;'],
 ['34281', 'B° LUCAS RODRIGUEZ M:;S/N;C C20;;'],
 ['34281', 'B° J.F.BOGADO MZ.I C.13;S/N;;MZ.I;'],
 ['34281', "Bø 544 VIV.-M.'J'-C.26-;S/N;;;"],
 ['34281', 'B° M.TORO MZ.;S/N;E.C:1;;'],
 ['34281', 'B° L.RODRIGUEZ MZ.F CS.10;S/N;;MZ.F;'],
 ['34281', 'B° J.DE D.GARRO MZ.E5 C.1;S/N;;MZ.E;'],
 ['34281', 'B° EL HORNERO MZ.3 C.5;S/N;;;'],
 ['34281', 'B° M.TORO MZ.D CS.1;S/N;;MZ.D;'],
 ['34282', 'B° M.LEZCANO MZ.I CS.3;S/N;;MZ.I;'],
 ['34282', 'BøEL LINCE MZA 36;S/N;C.22;;'],
 ['34282', 'B° 110 VIV. MZ.44 CS.1;S/N;;;'],
 ['34282', 'B° EL HORNERO M: G;S/N;C:05;;'],
 ['34282', 'B° EL HORNERO MZ.D C.24;S/N;;MZ.D;'],
 ['34282', 'B° EL HORNERO M:I;S/N;C:22;;'],
 ['34282', 'Bø EL LINCE MZ:;S/N;26C19;;'],
 ['34282', 'B° M.TORO MZ.B CS.2;S/N;;MZ.B;'],
 ['34282', 'B° M.LEZCANO MZ:K CS:21;S/N;;;'],
 ['34282', 'B° M.TORO MZ.G CS.15;S/N;;MZ.G;'],
 ['34283', 'B° TIBILETTI COSTANERA SU;S/N;1600;;'],
 ['34283', 'Bø M.LEZCANO M:7 C:9;S/N;;;'],
 ['34283', 'PLAN JOVENES 25/35 M:;S/N;C C11;;'],
 ['34283', 'B° M, TORO MZ.1;S/N;;;'],
 ['34283', 'B° SERRANIAS PUNT M: 44;S/N;C: 5;;'],
 ['34283', 'B° EL LINCE M:24 C:2;S/N;;;'],
 ['34283', 'Bø J.F.BOGADO;S/N;C:2;;'],
 ['34283', 'B° EL LINCE- MZ 21- C.5;S/N;;;'],
 ['34283', 'B° EL LINCE JOSE ZAVALA;S/N;795;;'],
 ['34283', 'B° 544 VIV. MZ.M CS.23;S/N;;;'],
 ['34284', 'Bø J.F.BOGADO;S/N;RC:17;;'],
 ['34284', 'B° SAN LUIS 23 ZONA SUR M;S/N;E C27;;'],
 ['34284', 'B° MAXIMILIANO TORO;S/N;H C19;;'],
 ['34284', 'B° M.LEZCANO;S/N;E C13;;'],
 ['34284', 'B° J.DEL SUR MZ.B CS.2;S/N;;MZ.B;'],
 ['34284', 'B° 544 VV. M:E;S/N;C:06;;'],
 ['34284', 'Bø J.DE DIOS GARRO;S/N;F6 C8;;'],
 ['34284', 'B° 110 VIV. MZ.196 C.16;S/N;;;'],
 ['34284', 'B° L.RODRIGUEZ MZ.I CS.9;S/N;;MZ.I;'],
 ['34284', 'B° 544 VIV. MZ.U CS.17;S/N;;;'],
 ['34285', 'B L. RODRIGUEZ M:B C:17;S/N;;;'],
 ['34285', 'B° J.F.BOGADO MZ.LL CS.8;S/N;;;'],
 ['34285', 'B° L.RODRIGUEZ M:;S/N;R C12;;'],
 ['34285', 'B° LUCAS RODRIGUEZ M:;S/N;I C:5;;'],
 ['34285', 'CALLE:45 CS:1266;S/N;;;'],
 ['34285', 'BøM.TORO M:;S/N;L.C:8;;'],
 ['34285', 'BøJ.DEL D.GARRO M:P C:7;S/N;;;'],
 ['34285', 'B° SAN LUIS XV MZ: D;S/N;CS:17;;'],
 ['34285', 'B° M.TORO MZ.M CS.9;S/N;;;'],
 ['34285', 'B° 114 VIV. MZ.188 CS.2;S/N;;;'],
 ['34286', 'B° M.TORO MZ.L CS.14;S/N;;;'],
 ['34286', 'B° J.F.BOGADO MZ.A CS.26;S/N;;MZ.A;'],
 ['34286', 'B° J.DE DIOS GARRO MZ.C3;S/N;CS.17;MZ.C;'],
 ['34286', 'B° SAN LUIS XV(15) MZ.I C;S/N;CS.3;MZ.I;'],
 ['34286', 'B° SAN LUIS XV(15) MZ.L C;S/N;CS.11;;'],
 ['34286', 'BøF.BOGADO MZ.A C.1;S/N;;MZ.A;'],
 ['34286', 'B° M.LEZCANO MZ.L CS.16;S/N;;;'],
 ['34286', 'B° 544 VIV. M:C;S/N;C:14;;'],
 ['34286', 'B° JARDIN DEL SUR M:;S/N;C C13;;'],
 ['34286', 'B° M.TORO MZ.C CS.12;S/N;;MZ.C;'],
 ['34287', 'B°JARDIN SUR MZ.G C.5;S/N;;MZ.G;'],
 ['34287', 'B° 110 VIV. M:194 C:13;S/N;;;'],
 ['34287', 'B° J.DEL SUR M:;S/N;I C27;;'],
 ['34287', 'B° J.F.BOGADO MZ.G CS.12;S/N;;MZ.G;'],
 ['34287', 'B° J.F.BOGADO MZ.M C.17;S/N;;;'],
 ['34287', 'B° L.RODRIGUEZ MZ:H CS:3;S/N;;;'],
 ['34287', 'Bø L.RODRIGUEZ MZ.A CS.27;S/N;;MZ.A;'],
 ['34287', 'B°E.DEL SUR M:;S/N;EC:61;;'],
 ['34287', 'Bø J.F.BOGADO M:;S/N;CC:28;;'],
 ['34287', 'B°J.DE DIOS GARRO M:;S/N;A1C11;;'],
 ['34288', 'B°F.BOGADO MZ.K C.27;S/N;;;'],
 ['34288', 'B° M.LEZCANO MZ:K;S/N;C:13;;'],
 ['34288', 'Bø SAN LUIS XV M:K;S/N;C:4;;'],
 ['34288', 'B° J.F.BOGADO MZ.L CS.24;S/N;;;'],
 ['34288', 'B° L.RODRIGUEZ MZ.I 9 CS.;S/N;1;MZ.I;'],
 ['34288', 'B° EL HORNERO MZ:D;S/N;C:18;;'],
 ['34288', 'B° EL HORNERO M:;S/N;E C26;;'],
 ['34288', 'B° SAN LUIS 23 M:B CS:3;S/N;;;'],
 ['34288', 'EL HORNERO;S/N;H-08;;'],
 ['34288', 'B° SAN LUIS XV(15) M:;S/N;JC:18;;'],
 ['34289', 'Bø.E.DEL SUR MZ:;S/N;F.C81;;'],
 ['34289', 'Bø M.TORO M:;S/N;G C17;;'],
 ['34289', 'B° L.RODRIGUEZ MZ.W CS.11;S/N;;;'],
 ['34289', 'B° EL HORNERO MZ.F CS.13;S/N;;MZ.F;'],
 ['34289', 'B° J.F.BOGADO MZ.Q CS.3;S/N;;;'],
 ['34289', 'B° 544 VIV. MZ.N CS.25;S/N;;;'],
 ['34289', 'B° PUCARA MZ.F CS.12;S/N;;MZ.F;'],
 ['34289', 'B° J.F.BOGADO MZ.K C.21;S/N;;;'],
 ['34289', 'B° M.TORO M:F;S/N;C:1;;'],
 ['34289', 'MANUEL LESCANO MZ. I C.N.;S/N;;;'],
 ['34290', 'B° J.DEL SUR MZ.D CS.11;S/N;;MZ.D;'],
 ['34290', 'B° 544 VDAS MZ.C CS.13;S/N;;MZ C;'],
 ['34290', 'B° SAN LUIS XXVI M:5 C:5;S/N;;;'],
 ['34290', 'B° VIRGEN DE LUJAN M:C;S/N;C:29;;'],
 ['34290', 'B° EL HORNERO MZ.C CS.27;S/N;;MZ.C;'],
 ['34290', 'B°J.DE DIOS GARRO MZ.C 14;S/N;;MZ.C;'],
 ['34290', 'Bø MANUEL LEZCANO MZ: L;S/N;C: 20;;'],
 ['34290', 'B° F.AMERICANOS MZ.B;S/N;CS.15;MZ.B;'],
 ['34290', 'B°L.RODRIGUEZ MZ.I CS.2;S/N;;MZ.I;'],
 ['34290', 'B° 109 VIV.M:B C:20;S/N;;;'],
 ['34291', 'B° EL LINCE MZ.23 CS.26;S/N;;;'],
 ['34291', 'B°PUCARA M:;S/N;F C21;;'],
 ['34291', 'B° EL LINCE MZ.24 CS.14;S/N;;;'],
 ['34291', 'Bø JARDIN DEL SUR M:D;S/N;C:9;;'],
 ['34291', 'RUTA 3 KM. 4;S/N;;;'],
 ['34291', 'B° EL LINCE MZ.20 CS.9;S/N;;;'],
 ['34291', 'BøEL LINCE MZ.23 CS.22;S/N;;;'],
 ['34291', 'Bø L.RODRIGUEZ MZA. U;S/N;C.11;;'],
 ['34291', 'B° 544 VIV. MZ.I CS.13;S/N;;MZ I;'],
 ['34291', 'SALVADOR SEGADO;S/N;C.9;;'],
 ['34292', 'Bø EL HORNERO MZ.J CS.14;S/N;;;'],
 ['34292', 'B° 110 VIV. MZ.191 CS.12;S/N;;;'],
 ['34292', 'B° SAN LUIS XV(15) M:;S/N;J C:3;;'],
 ['34292', 'B° E,DEL SUR MZA.E CS.59;S/N;;;'],
 ['34292', 'B°SAN LUIS XV MZ.J C.23;S/N;;;'],
 ['34292', 'B° EL HORNERO MZ.B C.2;S/N;;MZ.B;'],
 ['34292', 'BøEL HORNERO MZ.G C.2;S/N;;MZ.G;'],
 ['34292', 'B° 544 VDAS M:;S/N;N C:3;;'],
 ['34292', 'B° 500 VDAS M:143 C:15;S/N;;;'],
 ['34292', 'B° ESTRELLA DEL SUR MZA A;S/N;C:8;;'],
 ['34293', 'MAXIMILIANO TORO MZ: M;S/N;C:06;;'],
 ['34293', 'BøS.LUIS XXIII MZ:C :;S/N;C:7;;'],
 ['34293', 'MANUEL LEZCANO M: C;S/N;C:5;;'],
 ['34293', 'RUTA 3 KM 12;S/N;;;'],
 ['34293', 'B° MANUEL LEZCANO M:;S/N;D C:7;;'],
 ['34293', '544 VIVIENDAS MZA F;S/N;C:21;;'],
 ['34293', 'B° J.F.BOGADO MZ.LL CS.7;S/N;;;'],
 ['34293', 'B° 200 VIV.MUNICIPAL M:B;S/N;C:21;;'],
 ['34293', 'B° JARDIN DEL SUR;S/N;G C13;;'],
 ['34293', 'B° M.LEZCANO MZ.G CS.8;S/N;;MZ.G;'],
 ['34294', 'B° J.F.BOGADO MZ.K CS.6;S/N;;;'],
 ['34294', 'B° M.TORO MZ.Q C.14;S/N;;;'],
 ['34294', 'B° EL HORNERO MZ.E CS.2;S/N;;MZ.E;'],
 ['34294', 'B° J.F.BOGADO MZ.C CS.23;S/N;;MZ.C;'],
 ['34294', 'B° L.RODRIGUEZ MZ.G CS.4;S/N;;MZ.G;'],
 ['34294', 'Bø J.DEL SUR M:;S/N;D C:1;;'],
 ['34294', 'B° 144 VIV. M:;S/N;C C16;;'],
 ['34294', 'B° 500 VIV SUR M;S/N;161C6;;'],
 ['34294', 'B° J.F.BOGADO MZ.O C.36;S/N;;;'],
 ['34294', 'B°L.RODRIGUEZ MZ.H C.14;S/N;;MZ.H;'],
 ['34295', 'Bø PUCARA;S/N;BC:12;;'],
 ['34295', 'B° JARDIN DEL SUR MZ.B CS;S/N;23;MZ.B;'],
 ['34295', 'B° FELIX BOGADO M:C;S/N;C:07;;'],
 ['34295', 'B° M.TORO MZ.I CS.20;S/N;;MZ.I;'],
 ['34295', 'B°EL LINCE MZ.18 CS.22;S/N;;;'],
 ['34295', 'Bø M.TORO MZ.L CS.2;S/N;;;'],
 ['34295', 'SAN LUIS 26 MZ:3 CS:17;S/N;;;'],
 ['34295', 'B°EL HORNERO MZ.I C.12;S/N;;MZ.I;'],
 ['34295', 'B°EL LINCE M:30 C:5;S/N;;;'],
 ['34295', 'B° FELIX BOGADO M:C;S/N;C:14;;'],
 ['34296', 'B° J.DEL SUR MZ.G CS.6;S/N;;MZ.G;'],
 ['34296', 'B° LUCAS RODRIGUEZ M: Z;S/N;C:13;;'],
 ['34296', 'B°S.LUIS XV MZ.H C.26;S/N;;MZ.H;'],
 ['34296', 'B° M.LEZCANO MZ.M CS.22;S/N;;;'],
 ['34296', 'BøEL LINCE M:40 C:9;S/N;;;'],
 ['34296', 'B° J. DE DIOS GARRO M:F6;S/N;C:15;;'],
 ['34296', 'B°J.DEL SUR MZ.E C.20;S/N;;MZ.E;'],
 ['34296', 'LUCAS RODRIGUEZ MZ G;S/N;C:22;;'],
 ['34296', 'B° SAN LUIS XV MZ.Ñ CS.19;S/N;;;'],
 ['34296', 'B° 544 MZ.E C.22;S/N;;MZ E;'],
 ['34297', 'B° JARDIN SUR MZ.H C.17;S/N;;MZ.H;'],
 ['34297', 'B° L.RODRIGUEZ MZ.Z C.5;S/N;;;'],
 ['34297', 'B°L.RODRIGUEZ MZ.S C.12;S/N;;;'],
 ['34297', 'B° EL LINCE MZ.26 C.22;S/N;;;'],
 ['34297', 'B° M.LEZCANO MZ.C CS.10;S/N;;MZ.C;'],
 ['34297', 'B° S.LUIS 15 M:L C:20;S/N;;;'],
 ['34297', 'B° L.RODRIGUEZ M:P;S/N;C:19;;'],
 ['34297', 'B° M.TORO MZ.Q C.3;S/N;;;'],
 ['34297', 'Bø109 VDAS MZ.C CS.9;S/N;;MZ.C;'],
 ['34297', 'Bø109 VIV.MZ:;S/N;FC:18;;'],
 ['34298', 'B° J.F.BOGADO M:K C:14;S/N;;;'],
 ['34298', 'B° LUCAS RODRIGUEZ- MZ F;S/N;C 5;;'],
 ['34298', 'B° EL LINCE MZ.24 CS.16;S/N;;;'],
 ['34298', 'B° EL LINCE M:40 C:29;S/N;;;'],
 ['34298', 'B°S.LUIS 15 MZ.K C.18;S/N;;;'],
 ['34298', 'B°PUCARA M.E C.1;S/N;;;'],
 ['34298', 'Bø PUCARA MZ.A C.25;S/N;;MZ.A;'],
 ['34298', 'B° EL HORNERO M:H;S/N;C: 18;;'],
 ['34298', 'B° PUCARA MZ.F CS.1;S/N;;MZ.F;'],
 ['34298', 'B°F.BOGADO MZ:;S/N;K C:4;;'],
 ['34299', 'B° J.F.BOGADO M:E C:3;S/N;;;'],
 ['34299', 'B°EL LINCE MZ.31 C.5;S/N;;;'],
 ['34299', 'B°EL HORNERO M:;S/N;I C19;;'],
 ['34299', 'Bø EL LINCE-M.25-C.17-;S/N;;;'],
 ['34299', 'B° SAN LUIS XV(15) MZ.C C;S/N;CS.22;MZ.C;'],
 ['34299', 'B° ESTRELLA DEL SUR MZ:E;S/N;C:76;;'],
 ['34299', 'B° 110 VIV. MZ.194 CS.1;S/N;;;'],
 ['34299', 'B° EL LINCE MZ.20 CS.19;S/N;;;'],

3. Crear un `DataFrame` de `pandas`, llamado `domicilios_df`, con las columnas `ID` y `string_crudo`. El contenido debe ser la lista anidada creada arriba.

In [50]:
# Importo la librería pandas
import pandas as pd

# Creo un dataframe
domicilios_df = pd.DataFrame(domicilios_v2)
domicilios_df.rename({0:"ID", 1:"string_crudo"}, axis=1, inplace=True)

# Inspecciono el nuevo dataframe
domicilios_df

          ID                          string_crudo
0      34255       B° SAN LUIS XV(15);C: 03;;M: G;
1      34255       B° J.DE DIOS GARRO;C: 04;;M:LL;
2      34255           B° L.RODRIGUEZ;C: 05;;M: F;
3      34255       B° SAN LUIS XV(15);C: 05;;M: E;
4      34255        B° JARDIN DEL SUR;C: 06;;M: F;
...      ...                                   ...
26497  36904      Bø 500 VIV.SUR MZA.M:96;98;C.6;;
26498  36904            B° ESTRELLA DEL SUR;98;F;;
26499  36904              COSTANERA DEL SUR;988;;;
26500  36905                  BøEST.DEL SUR;99;F;;
26501  36905  B° JARDIN DEL SUR M: E C:;99;CS 99;;

[26502 rows x 2 columns]

4. Agregar al `DataFrame` las columnas `barrio`, `manzana`, `casa`, `lote` (todas de tipo `string`), pero inicialmente vacías (es decir, con `None`). En los siguientes incisos vamos a poblar estos campos usando expresiones regulares para parsear la columna `string_crudo`.

In [51]:
# Agrego las columnas barrio, manzana, casa, lote
domicilios_df["barrio"]=None
domicilios_df["manzana"]=None
domicilios_df["casa"]=None
domicilios_df["lote"]=None

# Inspecciono el dataframe
domicilios_df

          ID                          string_crudo barrio manzana  casa  lote
0      34255       B° SAN LUIS XV(15);C: 03;;M: G;   None    None  None  None
1      34255       B° J.DE DIOS GARRO;C: 04;;M:LL;   None    None  None  None
2      34255           B° L.RODRIGUEZ;C: 05;;M: F;   None    None  None  None
3      34255       B° SAN LUIS XV(15);C: 05;;M: E;   None    None  None  None
4      34255        B° JARDIN DEL SUR;C: 06;;M: F;   None    None  None  None
...      ...                                   ...    ...     ...   ...   ...
26497  36904      Bø 500 VIV.SUR MZA.M:96;98;C.6;;   None    None  None  None
26498  36904            B° ESTRELLA DEL SUR;98;F;;   None    None  None  None
26499  36904              COSTANERA DEL SUR;988;;;   None    None  None  None
26500  36905                  BøEST.DEL SUR;99;F;;   None    None  None  None
26501  36905  B° JARDIN DEL SUR M: E C:;99;CS 99;;   None    None  None  None

[26502 rows x 6 columns]

5. Empecemos primero analizando un `string_crudo` particular: `"B° SAN LUIS XV(15);C: 03;;M: G;"`

Escribir una expresión regular que contenga grupos (sub-expresiones regulares escritas entre paréntesis) y permita extraer los campos `barrio`, `manzana`, `casa` y `lote` del `string_crudo` anterior. Usarla para extraer estos campos en un diccionario. El resultado debería ser `{"barrio": "SAN LUIS XV(15)", "manzana": "G", "casa": "03"}`.

In [60]:
# Importo la librería re
import re

# Defino string particular
string = "B° SAN LUIS XV(15);C: 03;;M: G;"

# Defino expresión regular
re = re.search(r"^B°.(?P<barrio>.*?);M:.(?P<manzana>.*?);C:.(?P<casa>.*?);(L:)?(?P<lote>.*?);$", string)

# Creo diccionario
dict_string = {}

# Completo dicionario
keys = ["barrio", "manzana", "casa", "lote"]
for k in keys:
    try:
        dict_string[k] = re.group(k)
    except AttributeError:
        dict_string[k] = "null"

# Inspecciono el diccionario
print(dict_string)

{'barrio': 'null', 'manzana': 'null', 'casa': 'null', 'lote': 'null'}

6. Dependiendo de cómo hayan escrito la expresión regular anterior, puede ser más o menos general. Vamos a determinar cuántos domicilios satisfacen la expresión regular que escribieron en 5).
Para eso, crear un widget tipo `Textarea` donde puedan escribir una expresión regular, y una función reactiva a este widget (usando `ipywidgets.interact`) en que determine cuántos domicilios satisfacen la expresión regular e imprima este número. Realicen pequeños cambios a la expresión regular de manera que capture más casos.

In [13]:
# Importo la librería ipywidgets y el módulo interact de ésta
import ipywidgets as widgets
from ipywidgets import interact

#

7. Crear una nueva función para `interact`, basada en la función del punto 6), pero que reciba un segundo argumento, dado por un segundo widget que tome un valor booleano. Dependiendo de este valor, la función decidirá mostrar las filas de `domicilios_df` para las cuales la columna `string_crudo` satisface a la expresión regular del primer widget, o las que no la cumplen. Deben mirar la documentación de widgets para determinar qué tipo de widget usar en este caso: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html. Usar para los widgets una descripción adecuada.

8. En este ejercicio van a crear nuevas expresiones regulares para capturar tantos casos de domicilios como puedan, y lo van a hacer con la ayuda de los widgets que crearon anteriormente, de la siguiente manera. Primero, deben crear una copia de `domicilios_df` (obviamente, con algún otro nombre), una lista (inicialmente vacía) que se puede llamar `lista_regex`, y un widget tipo `Button` (ver [aquí](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Button)). Luego, van a realizar el siguiente procedimiento de manera iterativa.

- Usar el widget de `Textarea` para escribir una candidata a expresión regular.
- Chequear que la expresión regular permite extraer los campos correctamente para los casos en los que matchea. Si están satisfechos con esta expresión regular, presionar el widget `Button`, cuyo efecto será: 1) agregar la expresión regular a la lista `lista_regex` y 2) filtrar la copia del `domicilios_df` de manera de conservar sólo aquellas filas que no cumplen ninguna de las expresiones regulares que contiene `lista_regex`, incluida la agregada en el punto 1).
- Iterar en este procedimiento hasta tener una lista de unas ~10 expresiones regulares con bastante variedad.

_Deben dejar la lista de expresiones regulares que les quedó al final como comentario en el notebook, para que podamos probarlas al corregir._

In [ ]:
# regex_list = [regex1, regex2, ...]

9. Ahora poblemos los campos faltantes del DataFrame `domicilios_df`. Para eso, vamos a crear una función para ser pasada al método `apply` de DataFrame's. Esta función debe ser tal que reciba una lista de expresiones regulares (como la `lista_regex` de arriba), pruebe las mismas una a una, y si alguna matchea con `string_crudo`, pueble los campos restantes del `domicilios_df` con la información extraída.